### ISSUE TITLE
Make it possible to use already installed pyright

### ISSUE THREAD

**Issue by lovetox** [sublimelsp/LSP-pyright#101]
I have node installed, i have pyright installed, both in PATH

How can i configure the plugin to just use those, instead of downloading its own version, which seems to be hard coded in this plugin-package.

**Comment by rchl** [comment]
You can override `command` in user settings - https://github.com/sublimelsp/LSP-pyright/blob/2be205928f79a0e83979c2c47adf08f2c6669e7c/LSP-pyright.sublime-settings#L2

**Comment by lovetox** [comment]
thanks
