### ISSUE TITLE
Option to disable automatic triggering of the function help popup.

### ISSUE THREAD

**Issue by CAPTAIN1947** [sublimelsp/LSP-pyright#104]
**Is your feature request related to a problem? Please describe.**
pyright shows the parameter help popup every time I write a opening bracket parenthesis after a function.
I don't need the parameter help of the functions I use regularly. But I need it sometimes.

**Describe the solution you'd like**
So... I want to have a option to disable the automatic triggering of the popup. But that option shouldn't permanently disable it. It should only disable the automatic triggering.

**Additional context**
OS: Windows 10
Text Editor: Sublime 4121
And yes I tried to set ```"show_definitions"``` from sublime settings to false but it has no effects.

**Comment by rchl** [comment]
You can add:

```
    "disabled_capabilities": {
        "signatureHelpProvider": true,
    },
```

in LSP-pyright options.

**Comment by CAPTAIN1947** [comment]
> You can add:
> 
> ```
>     "disabled_capabilities": {
>         "signatureHelpProvider": true,
>     },
> ```
> 
> in LSP-pyright options.

But this is disabling it permanently. I also can't invoke it manually using ctrl-alt-space. I want to be able to invoke it manually.

**Comment by jfcherng** [comment]
> I want to be able to invoke it manually.

This sounds like a [LSP](https://github.com/sublimelsp/LSP) question then.

**Comment by rchl** [comment]
```
    "disabled_capabilities": {
        "signatureHelpProvider.triggerCharacters": true,
    },
```

**Comment by CAPTAIN1947** [comment]
Ohk thanks. Will try this. And is there any documentation for all the supported options. In the lsp-pyright settings the above mentioned options are not written anywhere.

**Comment by jfcherng** [comment]
> Ohk thanks. Will try this. And is there any documentation for all the supported options. In the lsp-pyright settings the above mentioned options are not written anywhere.

it's not pyright's setting but lsp's.

**Comment by CAPTAIN1947** [comment]
> > Ohk thanks. Will try this. And is there any documentation for all the supported options. In the lsp-pyright settings the above mentioned options are not written anywhere.
> 
> it's not pyright's setting but lsp's.

Oh. The first one was lsp-pyright's. So I thought that it would also be for the same.

**Comment by jfcherng** [comment]
> Oh. The first one was lsp-pyright's. So I thought that it would also be for the same.

Neither of them belongs to lsp-pyrght. all lsp.

**Comment by CAPTAIN1947** [comment]
I see. But can I get the list of available options from somewhere?

**Comment by rchl** [comment]
See https://lsp.sublimetext.io/guides/client_configuration/

**Comment by CAPTAIN1947** [comment]
:)

> See https://lsp.sublimetext.io/guides/client_configuration/

:) Thanks.
