### ISSUE TITLE
i have nodejs installed but twhen activating pyright for current project, this happens

### ISSUE THREAD

**Issue by JotSBRuh** [sublimelsp/LSP-pyright#116]
![image](https://user-images.githubusercontent.com/65026360/147114311-1451b54c-d713-410c-8581-4dc32e047b94.png)
i do have nodejs installed on PATH
![image](https://user-images.githubusercontent.com/65026360/147114484-c77928af-81d5-4f5f-a955-6804bd4ca5ab.png)
![image](https://user-images.githubusercontent.com/65026360/147114519-e8e2b37c-957c-40e3-a0b7-06da4fb3419a.png)

**Comment by rwols** [comment]
I think you need at least node v14

**Comment by predragnikolic** [comment]
See https://github.com/sublimelsp/LSP/issues/1671

**Comment by rchl** [comment]
As the error says, there should be more info in the ST console.

**Comment by JotSBRuh** [comment]
i just restarted sublime text and it worked sajdas
im sorry for the trouble
