### ISSUE TITLE
Add documentation about virtual environments

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-pyright#12]
Some users may be struggling with virtual environments.

Specifically, adding `VIRTUAL_ENV` to the project-specific `"env"` override makes things comfortable. But in general add a tutorial-style section on how to set things up for a virtual environment.

**Comment by Fingel** [comment]
For anyone else who is struggling to get this plugin to work, I believe what @rwols is referring to above is adding the following configuration to your sublime project's configuration file:

```
"settings":
	{
		"LSP":
		{
			"LSP-pyright":{
				"env":{
					"VIRTUAL_ENV": "/path/to/your/virtualenv"
				}
			}
		},
	},
}
```

The LSP-pyright key is case sensitive, it took me a while to figure that one out (I have another key that is lowercase and that one works, go figure).

With that config in place, using the LSP: Troubleshoot Server command will output some diagnostics and the `env` section should show something like this:
```
{
    "VIRTUAL_ENV": "/path/to/your/virtualenv"
}
```

Seems like a step in the right direction, though the language server still does not work.

**Comment by rchl** [comment]
I think this is now addressed with the current README.
