### ISSUE TITLE
Add documentation about pyrightconfig.json

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-pyright#13]
pyright can be configured with a pyrightconfig.json file. Add a tutorial-style section about this file and what it can do. Bonus points if there's also a section that explains how to mirror the settings in LSP-pyright.sublime-settings's `"settings"` key, and extra bonus points if there's a .sublime-project example for it to configure it per-project.

**Comment by rchl** [comment]
I'm not a fan of duplicating documentation as that can get out of sync easily.

I'd just link to original documentation and just explain potential differences that apply to ST.

**Comment by rwols** [comment]
OK, a link and possible differences would be sufficient documentation :)

**Comment by AmjadHD** [comment]
FWIW theres a schema for it https://raw.githubusercontent.com/microsoft/pyright/master/packages/vscode-pyright/schemas/pyrightconfig.schema.json

**Comment by desilinguist** [comment]
This is definitely needed. I just tried pyright and couldn't figure out how to customize it for a specific project. So, after a while I gave up and went back to the old Microsoft python language server. It's probably dead but at least it works and has documentation on how to configure it.

**Comment by jfcherng** [comment]
something like https://github.com/microsoft/pyright/blob/master/docs/configuration.md#sample-config-file ?

**Comment by Fingel** [comment]
I spent a bunch of time today trying to figure this out. From what I can tell, it necessary to have both a `pyrightconfig.json` file in you project's directory, and some other specific settings in your project's config file. Through trial and error, this is the minimal setup I've found that gets LSP-pyright to work correctly. Let us assume you have a project named "mypythonproj" and inside it a virtualenv named "env".

In my `project.sublime-project` settings file (command pallet: Project: Edit Project):

```json
{
	"folders":
	[
		{
			"folder_exclude_patterns":
			[
				"dist"
			],
			"path": "/path/to/mypythonproj/",
		}
	],
	"settings":
	{
		"LSP":
		{
			"LSP-pyright":{
				"settings":{
					"python.pythonPath": "/path/to/mypythonproj/env/bin/python3",
					"python.venvPath": "/path/to/mypythonproj/",
				}
			}
		},
	},
}
```

Additionally, there needs to be a `pyrightconfig.json` file in the root of the project directory:

```json
{
    "executionEnvironments": [
        {
          "root": "/path/to/mypythonproj/",
          "pythonVersion": "3.9",
          "venv": "env"
        }
    ]
}
```

Note that I actually put all my virtualenvs in a single folder, like ~/.virtualenvs/ so my "python.venvPath" is not actually my project folder. Note that in the pyrightconfig.json the "venv" config key is not a path to a virtualenvironment, it's the name of the virtual environment __within__ the folder containing it. Yea, I know.

All in all, this was a pretty painful experience. I'd be happy to open a PR with instructions to get this working (as the current README is completely blank) which I believe is necessary if this project ever has any hope of being used. But I'm not even sure my approach is correct.

**Comment by desilinguist** [comment]
Thank you so much for taking this on @Fingel! I have been struggling with the same thing for the past week and I couldn't agree more that the process is quite painful. Let me try and replicate your set up on my end and confirm whether it works with conda.

**Comment by rchl** [comment]
More minimal setup (avoiding specifying Python version and not using `executionEnvironments` which for simplicity can be skipped):

`*.sublime-project`:

```json
{
	"folders":
	[
		{
			"path": "/path/to/mypythonproj/",
		}
	],
	"settings":
	{
		"LSP":
		{
			"LSP-pyright":{
				"settings":{
					"python.venvPath": "/path/to/mypythonproj/",
				}
			}
		},
	},
}
```

`pyrightconfig.json`:

```json
{
    "venv": "env"
}
```

That's assuming that `/path/to/mypythonproj/` is a directory containing virtual environments and `env` being one of them.

**Comment by predragnikolic** [comment]
Shouldn't just having a `pyrightconfig.json` be sufficient? (without having to create a *.sublime-project file)

`pyrightconfig.json`
```
{
    "venvPath": "/path/to/mypythonproj/",
    "venv": "env"
}
```

**Comment by desilinguist** [comment]
Using the minimal setup reported by @rchl actually works for me with conda! However, only having pyrightconfig.json as suggested by @predragnikolic does not work.

**Comment by rchl** [comment]
@predragnikolic That also works (and it's also documented at https://github.com/microsoft/pyright/blob/master/docs/configuration.md) but it just might not be the best idea to have a path specific to your setup in a project that is potentially used by different developers.

**Comment by jfcherng** [comment]
Wondering will this get closed by https://github.com/sublimelsp/LSP-pyright/pull/34

**Comment by rwols** [comment]
Yeah I think this is sufficiently solved now

**Comment by plisdku** [comment]
I've been looking for an hour to find some documentation online about how to tell Pyright where my venv is with only my sublime-project file and this closed issue is the only place I have seen an example.

I am not convinced that LSP-pyright is getting _anything_ out of my sublime-project file. In particular, I can't see any evidence that settings.LSP.LSP-pyright is getting read by anything. For example,

```
{
    "folders":
    [
        {
            "path": "/path/to/folder"
        }
    ],
    "settings": {
        "LSP": {
            "LSP-pyright":{
                "settings":{
                    "python.venvPath": "/path/to/folder/containing/venv",
                    "python.venv": "venv",
                }
            }
        },
    }
}
```

all by itself seems like it ought to populate the same fields as the `pyrightconfig.json` file, if the comments above are correct. The README indeed says that

> The venvPath option can also be specified in your .sublime-project, in case you don't want to hard-code a system-specific path in a shared project.

But there is no example. Is this nested settings > LSP > LSP-pyright > python.XYZ method expected to work, and how can I troubleshoot this?

**Comment by rchl** [comment]
`python.venv` or `venv` is only supported in `pyrightconfig.json`.

If you have LSP-json then it will provide autocompletions for options that are supported. The ones that are not present there are not supported.

**Comment by plisdku** [comment]
Thanks @rchl , LSP-json made this much easier!

With LSP-json and after another pass through the readme, I realized I can get what I need by specifying the python interpreter path in my project like this. Pyright was then able to figure out everything else. I'll document this for posterity in case this can help someone else.

```
{
    "folders":
    [
        {
            "path": "/path/to/project"
        }
    ],
    "settings": {
        "LSP": {
            "LSP-pyright": {
                "settings": {
                    "python.pythonPath": "/path/to/venv/bin/python",
                }
            }
        }
    }
}
```
