### ISSUE TITLE
Pyright Cant find Node JS

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [sublimelsp/LSP-pyright#17]
Error M : Please install NodeJs for the server to work.

i have already installed in my linux, and can check node's version via terminal. but still i got a error messeage like above and doesnt work Pyright on SublimeText3
how can i solve this? 

os : pop os linux
node version  : 14.10.1
npm : 6.14.8

**Comment by rchl** [comment]
For SublimeText (and thus the server) be able to find Node executable, you need to make ST aware of the PATH where Node is.

On Linux (and Mac) you do that by augmenting or creating `~/.profile` file and either modifying PATH there with something like:

```
PATH="/path/where/node/is:$PATH"
```

**Remember to re-login or restart the computer after changing**

**Comment by JUNGHUNKIM-7** [comment]
> For SublimeText (and thus the package) be able to find Node executable, you need to make ST aware of the PATH where Node is.
> 
> On Linux (and Mac) you do that by augmenting or creating `~/.profile` file and either modifying PATH there with something like:
> 
> ```
> PATH="/path/where/node/is:$PATH"
> ```
> 
> or insert a relevant initialization script there if you are using something like `nvm` to manage node installations.
> 
> **Remember to re-login or restart the computer after changing**

thank you for your kindly answering. my node file(i installed via apt install nodejs) is in below directory. and i wrote it in profile, then save and reboot. but still not workable.

# Nodejs
PATH="/usr/bin/node:$PATH"

could you give me more advice for that?

**Comment by rchl** [comment]
You have to write the directory path where `node` is located, not the whole path to the binary. So:
```
PATH="/usr/bin/:$PATH"
```

**Comment by rwols** [comment]
But `/usr/bin` is most likely already in $PATH because it's a standard location.

**Comment by rchl** [comment]
The additional question: Was this package working before for you and just broke recently or you have just installed it? I'm asking because there was a change yesterday that could have broken it.

**Comment by rwols** [comment]
And also, what is the output of

```sh
node --version
```

in your terminal?

**Comment by JUNGHUNKIM-7** [comment]
> The additional question: Was this package working for you before and just broke recently, or have you just installed it? I'm asking because there was a change yesterday that could have broken it.

nope, im a newly installed it 2 or 3 days ago, and today im working on it by re-installing nodejs. but the last time was also being infinite looping to find server with same problem i asked today.

**Comment by JUNGHUNKIM-7** [comment]
> And also, what is the output of
> 
> ```shell
> node --version
> ```
> 
> in your terminal?

v14.10.1

**Comment by JUNGHUNKIM-7** [comment]
> You have to write the directory path where `node` is located, not the whole path to the binary. So:
> 
> ```
> PATH="/usr/bin/:$PATH"
> ```
> 
> Or maybe event better to put the path second so the utilities in `/usr/bin` don't override the ones in `PATH`:
> 
> ```
> PATH="$PATH:/usr/bin/"
> ```

i tried both, but cant have any chance to use your's haha. thank you

**Comment by rwols** [comment]
Please open the ST console by clicking on View > Show Console, and then paste the following in the console:

```
import shutil; shutil.which("node")
```
it should print `/usr/bin/node`, yes?

**Comment by JUNGHUNKIM-7** [comment]
When i try:
>>>import shutil; shutil.which("node")
(Nothing is shown, i checked node file(actually exist in /usr/bin) via "which node" in terminal) but isn't shown at sublime. that's strange, if it should be founded node's route in sublime)

>>> import os; os.environ["PATH"]
'/app/utils/bin:/app/sublime_merge/bin:/app/bin:/usr/bin'
(The Result)

thank you for keep helping my problem.

**Comment by rwols** [comment]
So node lives in `/usr/bin`, and `/usr/bin` is in your PATH, and ST sees `/usr/bin` in `os.environ["PATH"]`. but `shutil.which` cannot find node for some reason. :thinking:

**Comment by rchl** [comment]
`shutil.which` also checks file permissions and requires that the file is executable. Maybe also try this in ST console:
```py
import os; import stat; st = os.stat('/usr/bin/node'); oct_perm = oct(st.st_mode); print(oct_perm)
```

**Comment by JUNGHUNKIM-7** [comment]
well, i think that is not pyright's problem, im thinking there is some problem between node and sublime.

import os; import stat; st = os.stat('/usr/bin/node'); oct_perm = oct(st.st_mode); print(oct_perm)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/node'

after fixing it, will update it. Thank you guys so much!

**Comment by JUNGHUNKIM-7** [comment]
I finally solved the problem. Really thanks for 2 Developers!
All problems are brought from "Snap store's" Sublime Text! 

-- SOLUTION(LINUX) --
1. Install Node 
https://github.com/nodejs/help/wiki/Installation
2. Visit Sublime Official instead of downloading Sublime from Snap Store!
3. Install LSP and Pyright.
4. Done.

**Comment by Kakashiiiiy** [comment]
Hi, got the same problem now, but Sublime is able to locate Node, 

```
>>> import os; import stat; st = os.stat('/usr/bin/node'); oct_perm = oct(st.st_mode); print(oct_perm)
0o100755
>>> import shutil; shutil.which("node")
'/usr/bin/node'
```
755 means I have read and execute permissions. Not sure whats causing it. Removed Sublime and the whole config and did a plain install. But it does not work (Latest Arch Linux)

**Comment by Kakashiiiiy** [comment]
Got it, nodejs is not enought, NPM has to be installed as well. 

Maybe we should change the error message?

**Comment by jfcherng** [comment]
> Got it, nodejs is not enought, NPM has to be installed as well.
> 
> Maybe we should change the error message?

You would want to file an issue on https://github.com/sublimelsp/lsp_utils

**Comment by rchl** [comment]
The next `lsp_utils` version will show an error dialog when node fails to resolve with some extra information in the console.
