### ISSUE TITLE
Ingoring specific pep 8 warnings

### ISSUE THREAD

**Issue by fersarr** [sublimelsp/LSP-pyright#174]
Sorry if this is not the right place to ask, but I couldn't find information on how to disable specific PEP 8 warnings via the sublime text configuration files. Specifically, I want to disable warnings for PEP 8 W503 (please see screenshot snippet below).

![Screen Shot 2022-08-04 at 5 17 46 PM](https://user-images.githubusercontent.com/3913371/182899386-f67092f7-b643-468c-836d-b990ff51ad55.png)

**Comment by jfcherng** [comment]
If you google that, then you will know it's from flake8.

**Comment by fersarr** [comment]
@jfcherng I know that flake8 provides those messages but it only started appearing after I installed LSP-pyright and you can see in the image that it says LSP-pyright at the right edge of the message. So all I'm asking is what config json/text I need to put into the package's config file for sublime text to disable W503

**Comment by jfcherng** [comment]
I have told you in a affirmative tone that this has **NOTHING** to do with pyright. And even give you some hints with two links. Actually I have found the culprit. But I would like to leave it as your own work. Another final hint: yes, the culprit is in one of the two links.
