### ISSUE TITLE
LSP-pyright seems to need Sublime Text to be restarted to detect new additions

### ISSUE THREAD

**Issue by angrygoats** [sublimelsp/LSP-pyright#176]
It's entirely possible I am doing something wrong. 

My configuration seems correct. I am able to find existing libraries, imports, and project code. However if I add a new module to a package it seems that pyright does not automatically detect it. However, after closing and re-opening sublime text it works fine.

**Sublime Version**: Stable, Build 4126

`pyrightconfig.json`

```json
{
	// Install LSP-json to get validation and autocompletion in this file.
	"venvPath": "/Users/me/.pyenv/versions/",
	"venv": "proj",
	"executionEnvironments": [
		{"root": "proj_package"}
	]
}

```

`LSP-pyright.sublime-settings`

```json
// Settings in here override those in "LSP-pyright/LSP-pyright.sublime-settings"

{
  "settings": {
    "python.analysis.diagnosticSeverityOverrides": {
      "reportGeneralTypeIssues": "none"  // This will create problems with dynamic kwargs.
    }
  }
}

```

```Preferences.sublime-settings```

```json
{
	"translate_tabs_to_spaces": true,
	"detect_indentation": true,
	"vintage_use_clipboard": true,
	"rulers": [120],
	"tab_size": 2,
	"preview_on_click": false,
	"trim_trailing_white_space_on_save": "all",
	"scroll_past_end": true,
	"ignored_packages":
	[
		"Rust",
		"Six",
		"Vintage",
		"Vintageous",
	],
	"neovintageous_build_version": 11100,
	"added_words":
	[
		"Vintageous"
	],
}

```

**Comment by jfcherng** [comment]
https://github.com/sublimelsp/LSP-pyright#installation
See 2.

**Comment by angrygoats** [comment]
> See 2. https://github.com/sublimelsp/LSP-pyright/blob/f36a6e3b6659398c392f83e2b6449b430a4be2c5/README.md#installation

Ah...if only I could read. 

That worked. Thank you!
