### ISSUE TITLE
Disable auto-complete

### ISSUE THREAD

**Issue by dorianj** [sublimelsp/LSP-pyright#177]
When I open a function call, the pyright opens a dialog with the function's signature. I want to disable this, and only open it on some keypress. Is that possible? I have `"auto_complete": false,`  in my main Sublime preferences, which doesn't seem to apply here

**Comment by jfcherng** [comment]
If this can be done, it should be done in LSP rather than implement it in every LSP-*, so this should be a upstream issue. If you are interested in that, you can follow https://github.com/sublimelsp/LSP-json/issues/118 and it's referenced issue.

**Comment by rchl** [comment]
This is about signature help, as far as I understand
And disabling capability won't allow toggling it on key binding.

It sounds like a feature request for the LSP package anyway.
