### ISSUE TITLE
Linter is something weird

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [sublimelsp/LSP-pyright#18]
I got some linter messages whenever i loaded Modules.
it is actually installed already but i dont know why.

example: 
        1:6   	Pyright (reportMissingImports)	error     	Import "selenium" could not be resolved
        2:6   	Pyright (reportMissingImports)	error     	Import "selenium.webdriver.common.keys" could not be resolved
        3:6   	Pyright (reportMissingImports)	error     	Import "selenium.webdriver.common.by" could not be resolved
        4:6   	Pyright (reportMissingImports)	error     	Import "selenium.webdriver.support.ui" could not be resolved
        5:6   	Pyright (reportMissingImports)	error     	Import "selenium.webdriver.support" could not be resolved
        7:8   	Pyright (reportMissingImports)	error     	Import "pandas" could not be resolved
       68:32  	Pyright (reportUnboundVariable)	error     	"titles" is possibly unbound
       68:40  	Pyright (reportUnboundVariable)	error     	"prices" is possibly unbound

**Comment by rwols** [comment]
Are you using a virtualenv?

**Comment by JUNGHUNKIM-7** [comment]
> Are you using a virtualenv?

Yes i do.

**Comment by rwols** [comment]
If you're using a virtual env then you can create a .sublime-project and set up the `VIRTUAL_ENV` environment variable.

Click on Project > Save Project As... and save your project somewhere.
Then click on Project > Edit Project, and paste the following:

```js
// my-python-project.sublime-project
{
  "folders": [
    {
      "path": "/path/to/my-python-project"
    }
  ],
  "settings": {
    // Project-specific overrides for LSP.
    "LSP": {
      // Project-specific overrides for the LSP-pyright language server.
      "LSP-pyright": {
        // When starting the pyright process, override these
        // environment variables.
        "env": {
          // Inform pyright that we're using a virtual environment.
          "VIRTUAL_ENV": "${folder}/venv"
        }
      }
    }
  }
}
```

**Comment by jfcherng** [comment]
Will it be good if the following as the default for ST 4 since it's a convention?

```py
        "env": {
          // Inform pyright that we're using a virtual environment.
          "VIRTUAL_ENV": "${folder}/venv"
        }
```

**Comment by JUNGHUNKIM-7** [comment]
> If you're using a virtual env then you can create a .sublime-project and set up the `VIRTUAL_ENV` environment variable.
> 
> Click on Project > Save Project As... and save your project somewhere.
> Then click on Project > Edit Project, and paste the following:
> 
> ```js
> // my-python-project.sublime-project
> {
>   "folders": [
>     {
>       "path": "/path/to/my-python-project"
>     }
>   ],
>   "settings": {
>     // Project-specific overrides for LSP.
>     "LSP": {
>       // Project-specific overrides for the LSP-pyright language server.
>       "LSP-pyright": {
>         // When starting the pyright process, override these
>         // environment variables.
>         "env": {
>           // Inform pyright that we're using a virtual environment.
>           "VIRTUAL_ENV": "${folder}/venv"
>         }
>       }
>     }
>   }
> }
> ```
> 
> Since you're using ST3, you might need to change `"${folder}/venv"` into an absolute path (without the template string), but unsure if that's really the case.

// my-python-project.sublime-project
{
  "folders": [
    {
      "path": "/home/hun/바탕화면/PythonFiles"
    }
  ],
  "settings": {
    // Project-specific overrides for LSP.
    "LSP": {
      // Project-specific overrides for the LSP-pyright language server.
      "LSP-pyright": {
        // When starting the pyright process, override these
        // environment variables.
        "env": {
          // Inform pyright that we're using a virtual environment.
          "VIRTUAL_ENV": "/home/hun/anaconda3/envs/fizzbuzz"
        }
      }
    }
  }
}

I'm not sure i revise it correctly. thank you for replaying!

**Comment by JUNGHUNKIM-7** [comment]
> If you're using a virtual env then you can create a .sublime-project and set up the `VIRTUAL_ENV` environment variable.
> 
> Click on Project > Save Project As... and save your project somewhere.
> Then click on Project > Edit Project, and paste the following:
> 
> ```js
> // my-python-project.sublime-project
> {
>   "folders": [
>     {
>       "path": "/path/to/my-python-project"
>     }
>   ],
>   "settings": {
>     // Project-specific overrides for LSP.
>     "LSP": {
>       // Project-specific overrides for the LSP-pyright language server.
>       "LSP-pyright": {
>         // When starting the pyright process, override these
>         // environment variables.
>         "env": {
>           // Inform pyright that we're using a virtual environment.
>           "VIRTUAL_ENV": "${folder}/venv"
>         }
>       }
>     }
>   }
> }
> ```
> 
> Since you're using ST3, you might need to change `"${folder}/venv"` into an absolute path (without the template string), but unsure if that's really the case.

Thank you sir. Solved Everything, I edited LSP-Pyright's setting and your setting too. all problems are solved!

**Comment by herrmartins** [comment]
Hi!
I've setted up my virtualenv, as @rwols recommended and it works, BUT, with one thing it is not working... See print n the link below.
https://prnt.sc/KzYDPHVXiguh

The python line of code is  : 
venue_list = Venue.objects.all() - It is django ORM

but it shows an error: Cannot access member "objects" for type "Type[Venue]"

I tried just to shut it up with:
"reportFunctionMemberAccess":"false", - in the pyright.config.json,
but it doesn't stop showing this error...

**Comment by jfcherng** [comment]
For those framework specific issues, please do search them in [pyright](https://github.com/microsoft/pyright)'s repository as you are unlikely the first person who encountered them.

1. Search `django objects` => https://github.com/microsoft/pyright/issues?q=django+objects
2. Found https://github.com/microsoft/pyright/issues/3542
3. pip install `django-types`
4. Done.
