### ISSUE TITLE
Files outside project folders can't be diagnostics.

### ISSUE THREAD

**Issue by milkpuff** [sublimelsp/LSP-pyright#189]
If folders added to sublime_text side bar(add folders to project), a .py file out of those folders can't be diagnosed, and the output shows “No diagnostics. Well done!”. And files in those folders can be diagnosed.
If side bar is empty(no folder in project), any file can be diagnosed. 

So,  how can I add some folder to project and diagnose files outside project at the same time.

Settings as follow:
```{json}
{
	"settings": {
		"python.pythonPath": "G:/miniconda3/envs/py310/python.exe"
	}
}
```
env: win10, sublime_text 4, lsp-pyright 1.1.190

**Comment by jfcherng** [comment]
Not sure whether this is expected since I've seen single file mode works weird in several severs.

**Comment by jfcherng** [comment]
Just test in VSCode and it behaves so as well. Thus I would call this works as "expected".

**Comment by rchl** [comment]
There is code in LSP that ignores diagnostics for files outside of the workspace: https://github.com/sublimelsp/LSP/blob/c8e617caaffccb4f57799d9d8fa7588fa1048d52/plugin/core/sessions.py#L1682-L1684

**Comment by rchl** [comment]
It does not always make sense to ignore diagnostics outside of the project  so there is related issue in LSP: https://github.com/sublimelsp/LSP/issues/1835

**Comment by milkpuff** [comment]
@rchl @jfcherng 
Thanks very much.

> It does not always make sense to ignore diagnostics outside of the project so there is related issue in LSP: [sublimelsp/LSP#1835](https://github.com/sublimelsp/LSP/issues/1835)

Yes, this is the same problem.
It seems easy to handle in the code. But the work does not appear to be proceeding?

**Comment by rchl** [comment]
Such is life. Or open source at least.
Watch the issue for development or contribute with discussion or PR.
