### ISSUE TITLE
"organize imports" code action appears on every line

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-pyright#2]
I see a possible code action appearing anywhere in the file. It allows me to organize my imports. When I click on it, it "organizes" my imports. Now that my imports are organized I would expect to not see this code action anymore.

**Comment by jfcherng** [comment]
More like an issue for https://github.com/microsoft/pyright since it comes from the server while LSP just shows what it receives?

**Comment by rwols** [comment]
I suppose I'll open an issue there. But perhaps it's a configuration option that's missing.

**Comment by jfcherng** [comment]
Yeah... it should only shows on a `import xxx` line rather than every line...

**Comment by rchl** [comment]
I can't quite get pylance extension to work in VSCode to compare...

**Comment by rchl** [comment]
When implementing "get code actions on selection change", I've been said that that behavior is not something that VSCode does in general but it's specific to some server (golsp or some other one). But we still did that regardless. So the fact that it happens for us but not pyright is probably "by-design".

**Comment by rwols** [comment]
The "organize imports" code action will be a plain server command in the next release of pyright.
