### ISSUE TITLE
Unable to use pyright in PATH

### ISSUE THREAD

**Issue by lovetox** [sublimelsp/LSP-pyright#209]
Hi,

When i install LSP-Pyright it always donwloads pyright into some cache and use that instead of the one in PATH

Node 18 is installed, Pyright ist installed, both in PATH, yet i cannot prevent the server from downloading pyright and using that.

I tried deleting

`/home/lovetox/.cache/sublime-text/Package Storage/LSP-pyright/18.7.0/language-server/node_modules/pyright/dist/`

but it did not help

Im on Ubuntu 22.10

**Comment by jfcherng** [comment]
At this moment, no. If you must use your own pyright server, you can just use plain LSP with custom server settings. That will miss some feature provided by LSP-pyright though.

**Comment by lovetox** [comment]
I probably not using the right terms.

Is the project https://github.com/microsoft/pyright the server? or does this project here provide the server?

What i want to achieve is that i can use the pyright version i want.

i installed node and pyright globally.

And i would like that sublime uses that global installation to type check the codebase.

how would i need to adjust "command" so that it uses the global installed pyright in PATH?

**Comment by jfcherng** [comment]
> Is the project [microsoft/pyright](https://github.com/microsoft/pyright) the server? 

yes, it is.

> or does this project here provide the server?

LSP-pyright downloads pyright and manage it for users.

> how would i need to adjust "command" so that it uses the global installed pyright in PATH?

From LSP-pyright's settings.

**Comment by lovetox** [comment]
Thanks, i close as this works for me.
