### ISSUE TITLE
stub files, dependencies, and the sys.path

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-pyright#21]
<img width="796" alt="Schermafbeelding 2020-10-03 om 23 15 05" src="https://user-images.githubusercontent.com/2431823/95002065-69b8fe80-05d0-11eb-96d0-009b62283e1e.png">

I have mdpopups in one of my stub files here https://github.com/sublimelsp/LSP/blob/st4000-exploration/stubs/mdpopups.pyi

Why doesn't pyright see my stub files?

Perhaps more fundamentally, how can we get pyright to understand Package Control dependencies so we can omit stub files altogether? The file structure looks like this:

```
raoulwols@MacBook-Pro-van-Raoul ~/L/A/S/Packages> pwd
/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages
raoulwols@MacBook-Pro-van-Raoul ~/L/A/S/Packages> ls -lash mdpopups
total 72
0 drwxr-xr-x  14 raoulwols  staff   448B 30 aug 00:11 ./
0 drwx------  46 raoulwols  staff   1,4K  3 okt 21:56 ../
8 -rw-r--r--   1 raoulwols  staff    43B 30 aug 00:11 .gitattributes
8 -rw-r--r--   1 raoulwols  staff   735B 30 aug 00:11 .gitignore
8 -rw-r--r--   1 raoulwols  staff   2,5K 30 aug 00:11 .pyspelling.yml
8 -rw-r--r--   1 raoulwols  staff   1,1K 30 aug 00:11 LICENSE.md
8 -rw-r--r--   1 raoulwols  staff   2,0K 30 aug 00:11 Preferences.sublime-settings
8 -rw-r--r--   1 raoulwols  staff   3,4K 30 aug 00:11 README.md
8 -rw-r--r--   1 raoulwols  staff   185B 30 aug 00:11 dependency-metadata.json
0 drwxr-xr-x   3 raoulwols  staff    96B 11 jul 00:18 mdpopups_css/
8 -rw-r--r--   1 raoulwols  staff   3,2K 30 aug 00:11 mkdocs.yml
0 drwxr-xr-x   3 raoulwols  staff    96B  4 aug  2017 st3/
0 drwxr-xr-x   5 raoulwols  staff   160B 11 jul 00:18 tests/
8 -rw-r--r--   1 raoulwols  staff   510B 30 aug 00:11 tox.ini
```

The actual implementation of mdpopups lives in an `st3` subfolder. Indeed, printing my sys.path **in the python 3.3 interpreter** of ST4 prints these paths:

```
Python 3.3>>> import sys
Python 3.3>>> sys.path
['/Applications/Sublime Text.app/Contents/MacOS/Lib/python3.3.zip', '/Applications/Sublime Text.app/Contents/MacOS/Lib/python33', '/Applications/Sublime Text.app/Contents/MacOS/Lib/python3', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Lib/python33', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pygments/all', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/ruamel-yaml/st3', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/sublime_lib/st3', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/tabulate/all', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/lsp_utils/st3', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/wcwidth/all', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/coverage/st3_osx_x64', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/ptyprocess/all', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/backrefs/st3', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/bracex/st3', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/markupsafe/all', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pathlib/all', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pymdownx/st3', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pyte/all', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/pyyaml/st3', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/python-jinja2/all', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/wcmatch/st3']
```

All of these paths should be added to pyright's extra paths during startup, *but only for ST plugin development*. It doesn't make much sense to have these paths for:

- Standalone python development
- Python running in a virtual environment
- Blender plugins
- GIMP plugins
- GDB plugins

IMO, we should think carefully about how to set up the import environment for end-users.

**Comment by jfcherng** [comment]
> I have mdpopups in one of my stub files here [https://github.com/sublimelsp/LSP/blob/st4000-exploration/stubs/mdpopups.pyi](https://github.com/sublimelsp/LSP/blob/st4000-exploration/stubs/mdpopups.pyi?rgh-link-date=2020-10-03T21%3A47%3A10Z)
> 
> Why doesn't pyright see my stub files?

I didn't try but did you set `python.analysis.stubPath` to `./stubs`?

**Comment by rwols** [comment]
My point is that the execution environment of pyright is totally wrong.

When I "goto" to the definition of some standard library construct, pyright jumps to a file of the global python interpreter of my system. It should instead analyze `/Applications/Sublime Text.app/Contents/MacOS/Lib/python3.3.zip`, and then conclude that it cannot show the definition because it's in a pre-compiled .pyc file inside a .zip file.

**Comment by rwols** [comment]
Essentially the python interpreter for plugin development is plugin_host-3.3, how can we get pyright to understand that?

**Comment by rchl** [comment]
If it would be using 3.3 environment then, I think, typing would not work since types work from 3.5.

**Comment by rwols** [comment]
Okay, I suppose it has to emulate 3.8 behavior for the typing to work. But in any case I have this in my .sublime-project file now and it still cannot find mdpopups:

```json
{
	"folders":
	[
		{
			"path": "."
		},
		{
			"path": "../LSP-eslint"
		},
		{
			"path": "../User"
		},
		{
			"path": "/Users/raoulwols/dev/tonic"
		},
		{
			"path": "../LSP-lua"
		},
		{
			"path": "../LSP-PowerShellEditorServices"
		},
		{
			"path": "../sublime_asyncio_loop"
		},
		{
			"path": "../LSP-OmniSharp"
		},
		{
			"path": "../LSP-pyls"
		},
		{
			"path": "/Users/raoulwols/dev/LSP-SonarLint"
		}
	],
	"settings":
	{
		"lsp_format_on_save": false,
		"rulers": [120],
		"LSP":
		{
			"LSP-pyright": {
				"settings": {
					"python.analysis.stubPath": "./stubs",
					"python.pythonPath": "python3",
					"python.analysis.extraPaths": [
						"${sublime_py_files_dir}",
						"${packages}",
						"${packages}/mdpopups/st3"
					]
				}
			}
		}
	}
}
```

I can see it asking for the section and LSP is returning the correct dict:
```
:: <-- LSP-pyright workspace/configuration(1): {'items': [{'scopeUri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP', 'section': 'python'}]}
:: >>> LSP-pyright 1: [{'pythonPath': 'python3', 'venvPath': '', 'analysis': {'logLevel': 'info', 'stubPath': './stubs', 'autoImportCompletions': True, 'autoSearchPaths': True, 'diagnosticMode': 'openFilesOnly', 'diagnosticSeverityOverrides': {}, 'typeCheckingMode': 'basic', 'useLibraryCodeForTypes': True, 'extraPaths': ['/Applications/Sublime Text.app/Contents/MacOS/Lib/python33', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages', '/Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3'], 'typeshedPaths': []}}]
```

But goto-def on `import mdpopups` doesn't work:

```
:: --> LSP-pyright textDocument/definition(15): {'position': {'line': 0, 'character': 10}, 'textDocument': {'uri': 'file:///Users/raoulwols/Library/Application%20Support/Sublime%20Text%203/Packages/LSP/plugin/completion.py'}}
:: <<< LSP-pyright 15: None
```

**Comment by rwols** [comment]
Note that I renamed the stubs/ folder for this because otherwise it jumps to the stub file. I want it to jump to the actual implementation in /Users/raoulwols/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3

**Comment by rwols** [comment]
I give up. I tried to get things to work with a pyrightconfig.json file and manually running `pyright` in my terminal. But it gets really confused about the `sublime_api` module, and there are also problems with an `exception` module somewhere in the stdlibs for some reason. Stubs seem like the way to go. I might follow this up on the pyright repo because it looks like pyright doesn't really handle embedded interpreter environments all that well (GDB, GIMP, blender, etc)
