### ISSUE TITLE
Vendor Python syntax or drop ST 3

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/LSP-pyright#220]
because the Python syntax is going to be v2 in https://github.com/sublimehq/Packages/pull/3650 and we extend it in https://github.com/sublimelsp/LSP-pyright/blob/master/syntaxes/pyright.sublime-syntax

**Comment by rchl** [comment]
Dropping seems perfectly fine to me. We can fork ST3-branch and leave it at that.

**Comment by jfcherng** [comment]
I would bundle v1 syntax https://github.com/sublimelsp/LSP-pyright/pull/223 to have a smoother transition when v2 syntax just comes out. When our v2 syntax is ready and the next ST version which uses v2 syntax, we cut new releases into ST4-only and drop the bundled v1 syntax.
