### ISSUE TITLE
Package Control marks LSP-pyright as "incompatible" when starting Sublime

### ISSUE THREAD

**Issue by genericusername3** [sublimelsp/LSP-pyright#234]
![image](https://user-images.githubusercontent.com/42579023/225870734-24901cb4-adce-494b-8696-45ba5cf75357.png)

I'm on Manjaro Linux and this occurs after I upgraded to Sublime 4148 (don't know the previous version), if that's of any help

**Comment by jfcherng** [comment]
Does it only popup one time, or this happen everytime you start ST?

**Comment by jfcherng** [comment]
We do have some changes for LSP-pyright in https://github.com/sublimelsp/repository/blob/dc7ef04096b9d2758ce15a8ef9960727e40ae138/repository.json#L642-L651. But from my test, I can install it with clean ST 4148 without any error. Can you try to reinstall it?

**Comment by rchl** [comment]
Or try "Package Control: Upgrade Package"

**Comment by jfcherng** [comment]
It should use `"version": "1.2.29", "sublime_text": ">=4148"`.
