### ISSUE TITLE
Settings python.analysis.extraPaths Conflict with pyrightconfig extraPaths

### ISSUE THREAD

**Issue by munkybutt** [sublimelsp/LSP-pyright#241]
Hey - I am trying to add paths to my `.sublime-project` file using `"python.analysis.extraPaths"`.
This is used to add project specific paths on top of the paths in my `pyrightconfig.json` file.
The `pyrightconfig.json` is used to define shared settings for a number of projects that have the same set of dependencies as well as sharing pyright settings with vscode projects.
It seems that project settings are ignored if the `pyrightconfig.json` file already has `"extraPaths"` defined:
```json
"settings":
{
    "LSP": {
        "LSP-pyright": {
            "settings": {
                "python.analysis.extraPaths": [
                    // paths here
                ]
            }
        }
    }
}
```
This is the same behaviour if I define `"python.analysis.extraPaths"` in the LSP-pyright global settings, `pyrightconfig.json` takes precedence. 

If this is intentional is it possible to update the behaviour to be additive rather than exclusive?

**Comment by jfcherng** [comment]
I am not convinced that this is an issue of LSP-pyright but pyright. LSP-pyright merge project settings with plugin settings and send it to pyright. That's all.

**Comment by munkybutt** [comment]
If I replicate this setup in VSCode ( `pyrightConfig.json` with `"extraPaths"` defined and then define `"python.analysis.extraPaths"` in the `.workspace` file the behaviour is that the two lists are merged - which is the behaviour I was expecting with Sublime 😢

**Comment by jfcherng** [comment]
Closed as I don't think this issue belongs to LSP-pyright, but pyright (though I don't think they will change this behavior).
