### ISSUE TITLE
Do Relative Paths Work in .sublime-project Files?

### ISSUE THREAD

**Issue by munkybutt** [sublimelsp/LSP-pyright#243]
Hey - In an attempt to work around https://github.com/sublimelsp/LSP-pyright/issues/241 I am trying to move all my LSP-pyright settings to my `.sublime-project` file.
Relative paths don't seem to work though, is this intentional?
It might not be a LSP-pyright issue, but relative paths work in other areas of `.sublime-project` files and they work in VSCode `.workspace` files.

This is the behaviour I am experiencing:

![relative_paths](https://user-images.githubusercontent.com/7100563/234822940-fa3957c5-60ae-47e1-bac3-47e514273786.gif)

Any insight is appreciated.

**Comment by munkybutt** [comment]
Cool ok - so it should work in Sublime.
I will investigate further, likely it is another plugin preventing this from working as expected.

**Comment by munkybutt** [comment]
So it looks like the paths are resolved relative to each folder in the project, rather than the `.sublime-project` file itself - which makes perfect sense.

**Comment by jfcherng** [comment]
Those (relative or absolute) paths will be passed to the pyright server as-is. But I don't know what will happen on the server-side for relative paths indeed (e.g., does it support relative paths? relative to what?).

**Comment by nicbou** [comment]
I ended up using an absolute path, but this makes the project a lot flakier
