### ISSUE TITLE
Extra features available in coc.pyright

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-pyright#249]
Just as a FYI in case it's not a common knowledge: coc.pyright implements a bunch of extra features on top of pyright, including semantic highlighting and inlay hints. Haven't tried it myself.

https://github.com/fannheyward/coc-pyright

After brief look I think we could (if someone has a a need, will and time) take some of that code and support those features here by building pyright ourselves  with those features added as patches.

**Comment by jfcherng** [comment]
~Or submit PRs to pyright 😂, though pretty sure they can, already, strip those codes from pylance but for some reasons they don't.~

Coc-pyright implementation is currently bound to nvim. Making a custom pyright with patches will make it available to all editors.

**Comment by jfcherng** [comment]
I think now [DetachHead/basedpyright](https://github.com/DetachHead/basedpyright) is prefered over coc's.

ref: https://github.com/sublimelsp/LSP-pyright/issues/317
