### ISSUE TITLE
LSP-pyright can't see my Pip packages

### ISSUE THREAD

**Issue by imZawgg** [sublimelsp/LSP-pyright#277]
Trying to use discord.py with Sublime.
Package list: 
- ayu & a file icon
- LSP 
- LSP-file-watcher-chokidar
- LSP-pyright
- Package Control
- Terminus

`Import "discord" could not be resolved Pyright(reportMissingImports)`

**Comment by jfcherng** [comment]
- How do you install `discord` package? 
- Is there any virtual environment involved?
- What's the output of `which pip` in your terminal?

**Comment by imZawgg** [comment]
- Yes, I've installed discord. `Requirement already satisfied: discord in c:\users\hughb\appdata\local\programs\python\python311\lib\site-packages (2.1.0)`
- No, there is not a virtual environment.
- I am on windows, I do not have the "which" command. I did some digging and found "C:\Users\hughb\AppData\Local\Programs\Python\Python311\Scripts\pip.exe" as the path, though

**Comment by jfcherng** [comment]
Not sure whether this is important but is `python` in your `PATH` env? You can test this by executing `import shutil; shutil.which('python')` in ST's console.

**Comment by jfcherng** [comment]
I see your post on the forum: https://forum.sublimetext.com/t/lsp-pyright-cant-see-my-pip-packages/69950

Did you try to restart ST?

**Comment by imZawgg** [comment]
I've restarted ST multiple times during troubleshooting.

Using shutil, the output by printing is:
`C:\Users\hughb\AppData\Local\Programs\Python\Python311\python.EXE`

**Comment by jfcherng** [comment]
Is there a `LSP-pyright: Using python path "XXXXXXX"` msg in ST console?

**Comment by blag** [comment]
I'm having the same issue, using Poetry on macOS.

Sublime build 4152
Package Control v3.4.1
LSP v1.26.0
LSP-pyright v1.2.51

I have verified that my virtualenv is valid and activated in my terminal and contains packages that I have installed with Poetry.

LSP-pyright correctly finds issues in my code, but incorrectly identifies packages that are installed in my virtualenv as missing:

```
Import "django.dispatch" could not be resolved
```

I removed and re-installed LSP-pyright and restarted Sublime Text and have the same issue as before.

I can see `LSP-pyright: Using python path "python"` three times in my Sublime Console log right after Sublime starts up.

The `shutil` trick does not return anything when I search for `python`, but it does when I use `shutil.which("python3")`:

```python
>>> shutil.which("python3")
'/usr/bin/python3'
```

Note that this is _not_ the python executable available in my virtualenv.

When I run `import sys; sys.version`, I get this:

```
'3.8.12 (default, Dec  7 2022, 15:00:02) \n[Clang 15.0.3 (https://github.com/tru/llvm-release-build c98e08626c3c6d4f184f49'
```

For reference, I have installed the pyright CLI via npm and that works perfectly when I have it check a file in my project, and it also correctly finds syntax issues when I intentionally introduce them in my Python file.

My (redacted) `pyrightconfig.json` file is:

```jsonc
{
	// Install LSP-json to get validation and autocompletion in this file.
	"venvPath": "/Users/(redacted username)Library/Caches/pypoetry/virtualenvs/",
	"venv": "(redacted name)-(redacted hash?)-py3.11",
	"verboseOutput": true,
}
```

I believe that this verifies that `pyright` is correctly reading my `pyrightconfig.json` file and loading packages from my configured virtualenv.

Please advise.

**Comment by blag** [comment]
I found one way that works.

According to [this comment](https://github.com/sublimelsp/LSP-pyright/issues/226#issuecomment-1656997778), you can specify a path to the Python **executable** in your virtualenv in the Sublime Project (`<project>.sublime-project`) configuration:

```json
{
    "settings": {
        "LSP": {
            "LSP-pyright": {
                "settings": {
                    "python.pythonPath": "/Users/(redacted username)/Library/Caches/pypoetry/virtualenvs/(redacted name)-(redacted hash?)-py3.11/bin/python3.11",
                },
            },
        },
    },
}
```

However, it is not optimal to have to specify the same config in two different files, so I think this is still a bug.

**Comment by imZawgg** [comment]
Thx @blag, but Im not using poetry, Im using PiPy a.k.a. Pip.

**Comment by imZawgg** [comment]
> Is there a `LSP-pyright: Using python path "XXXXXXX"` msg in ST console?

 Again, Im on windows, I do not have a console.

**Comment by blag** [comment]
The underlying issue, where pyright does not see packages installed in a virtualenv, is the same. The package manager - Pip or Poetry - is probably not a difference that matters.

**Comment by jfcherng** [comment]
@blag Your case looks totally fine to me. You can either modify it to use `python3` rather than `python` or assign a full path. I don't see any issue there.

---

> Is there a LSP-pyright: Using python path "XXXXXXX" msg in ST console?
> Again, Im on windows, I do not have a console.

I am not asking a console but ST console. (``ctrl+` ``). Yet, `cmd` / `powershell` are consoles too.

**Comment by imZawgg** [comment]
O.M.G. Thank you for letting me know about ctrl+` . Apparently, it WAS using another path, in fact a random venv from an old PyCharm Project.

**Comment by jfcherng** [comment]
> O.M.G. Thank you for letting me know about ctrl+` . Apparently, it WAS using another path, in fact a random venv from an old PyCharm Project.

Do you mind providing the path of the "random" venv for further investigation why this happens?

**Comment by imZawgg** [comment]
C:\Users\hughb\pythonProject2\Scripts

**Comment by blag** [comment]
@jfcherng Should I open a new issue for my problem?

**Comment by jfcherng** [comment]
> @jfcherng Should I open a new issue for my problem?

Sure. It would make discussion more clear. Though I don't see any issue at this moment.

**Comment by jfcherng** [comment]
> C:\Users\hughb\pythonProject2\Scripts
> 
> P.S. For some reason, even after defining the right path in the LSP-pyright config, I still had to delete the path before it was fixed..

Do you have any of the following file in your project root?

- Pipfile
- poetry.lock
- .python-version

What's the path of your project root?
