### ISSUE TITLE
Removing LSP-pyright gives error

### ISSUE THREAD

**Issue by blag** [sublimelsp/LSP-pyright#278]
Sublime throws up an error when I remove the LSP-pyright package from Sublime's command palette:

> Error loading syntax file "Packages/LSP-pyright/syntaxes/pyright.sublime-syntax": Unable to read Packages/LSP-pyright/syntaxes/pyright.sublime-syntax

Sublime build 4152
Package Control v3.4.1

**Comment by jfcherng** [comment]
Just restart ST or ignore it.

**Comment by rchl** [comment]
You will probably have to also close the affected python files and optionally reopen them to fix this.
