### ISSUE TITLE
The "sublime_text" dev environment should also allow setting 3.3 or 3.8 as target

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-pyright#28]
We now have a "sublime_text" dev environment setting. This is cool.

One improvement to this is to also pin down the python version in use. I think this is settable in the executionEnvironment array. There are two "sublime_text" dev environments, namely Python 3.3 and Python 3.8. A user should be able to pick one of the two for his/her plugin. I propose using "sublime_text_33" and "sublime_text_38" as enums.

**Comment by jfcherng** [comment]
Since we are using the `sys.path` approach and LSP is not running both on 3.3 and 3.8 at the same time simultaneously. How will we determinate the `extraPaths` for `sublime_text_38`?

**Comment by rwols** [comment]
I'm playing around with https://github.com/sublimelsp/sublime_asyncio and I kind of need this.

In `find_package_dependency_dirs` we copy the sys paths. If one of those paths ends with `Lib/python33`, then that path should be replaced with a `Lib/python38` suffix if the user wants a py38 environment perhaps.

For example I have two such paths in my sys path:

```
/Users/raoulwols/Library/Application Support/Sublime Text 3/Lib/python38
/Applications/Sublime Text.app/Contents/MacOS/Lib/python38
```
