### ISSUE TITLE
Error while updating plugin, the following is the log information

### ISSUE THREAD

**Issue by matresnan** [sublimelsp/LSP-pyright#301]
0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@9.8.1
2 info using node@v18.18.0
3 timing npm:load:whichnode Completed in 7ms
4 timing config:load:defaults Completed in 18ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 8ms
6 timing config:load:builtin Completed in 10ms
7 timing config:load:cli Completed in 15ms
8 timing config:load:env Completed in 3ms
9 timing config:load:file:E:\Sublime_Text4\Data\Package Storage\LSP-pyright\18.18.0\language-server\.npmrc Completed in 1ms
10 timing config:load:project Completed in 6ms
11 timing config:load:file:C:\Users\admin\.npmrc Completed in 2ms
12 timing config:load:user Completed in 3ms
13 timing config:load:file:C:\Users\admin\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 2ms
15 timing config:load:setEnvs Completed in 5ms
16 timing config:load Completed in 62ms
17 timing npm:load:configload Completed in 63ms
18 timing config:load:flatten Completed in 14ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm ci
22 verbose argv "ci" "--omit" "dev" "--scripts-prepend-node-path" "true" "--loglevel" "verbose"
23 timing npm:load:setTitle Completed in 5ms
24 timing npm:load:display Completed in 8ms
25 verbose logfile logs-max:10 dir:C:\Users\admin\AppData\Local\npm-cache\_logs\2024-01-22T09_45_08_595Z-
26 verbose logfile C:\Users\admin\AppData\Local\npm-cache\_logs\2024-01-22T09_45_08_595Z-debug-0.log
27 timing npm:load:logFile Completed in 46ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 239ms
31 timing arborist:ctor Completed in 4ms
32 silly logfile start cleaning logs, removing 2 files
33 timing idealTree:init Completed in 47ms
34 timing idealTree:userRequests Completed in 1ms
35 silly idealTree buildDeps
36 timing idealTree:#root Completed in 0ms
37 timing idealTree:buildDeps Completed in 6ms
38 timing idealTree:fixDepFlags Completed in 0ms
39 timing idealTree Completed in 62ms
40 timing npm-ci:rm Completed in 1ms
41 silly logfile done cleaning log files
42 timing reify:loadTrees Completed in 10ms
43 timing reify:diffTrees Completed in 4ms
44 silly reify moves {}
45 timing reify:retireShallow Completed in 4ms
46 timing reify:createSparse Completed in 4ms
47 timing reify:trashOmits Completed in 1ms
48 timing reify:loadBundles Completed in 0ms
49 silly audit bulk request { fsevents: [ '2.3.3' ], pyright: [ '1.1.347' ] }
50 verbose reify failed optional dependency E:\Sublime_Text4\Data\Package Storage\LSP-pyright\18.18.0\language-server\node_modules\fsevents
51 silly reify mark deleted [
51 silly reify   'E:\\Sublime_Text4\\Data\\Package Storage\\LSP-pyright\\18.18.0\\language-server\\node_modules\\fsevents'
51 silly reify ]
52 timing reifyNode:node_modules/fsevents Completed in 217ms
53 silly tarball no local data for pyright@https://registry.npm.taobao.org/pyright/-/pyright-1.1.347.tgz. Extracting by manifest.
54 silly audit bulk request failed undefined
55 verbose audit error FetchError: request to https://registry.npm.taobao.org/-/npm/v1/security/audits/quick failed, reason: certificate has expired
55 verbose audit error     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
55 verbose audit error     at ClientRequest.emit (node:events:517:28)
55 verbose audit error     at TLSSocket.socketErrorListener (node:_http_client:501:9)
55 verbose audit error     at TLSSocket.emit (node:events:529:35)
55 verbose audit error     at emitErrorNT (node:internal/streams/destroy:151:8)
55 verbose audit error     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
55 verbose audit error     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
55 verbose audit error   code: 'CERT_HAS_EXPIRED',
55 verbose audit error   errno: 'CERT_HAS_EXPIRED',
55 verbose audit error   type: 'system'
55 verbose audit error }
56 silly audit error undefined
57 timing auditReport:getReport Completed in 489ms
58 silly audit report null
59 timing reify:audit Completed in 490ms
60 timing reify:rollback:createSparse Completed in 7ms
61 timing reify:rollback:retireShallow Completed in 0ms
62 timing command:ci Completed in 70845ms
63 verbose type system
64 verbose stack FetchError: request to https://registry.npm.taobao.org/pyright/-/pyright-1.1.347.tgz failed, reason: certificate has expired
64 verbose stack     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
64 verbose stack     at ClientRequest.emit (node:events:517:28)
64 verbose stack     at TLSSocket.socketErrorListener (node:_http_client:501:9)
64 verbose stack     at TLSSocket.emit (node:events:529:35)
64 verbose stack     at emitErrorNT (node:internal/streams/destroy:151:8)
64 verbose stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
64 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
65 verbose cwd E:\Sublime_Text4\Data\Package Storage\LSP-pyright\18.18.0\language-server
66 verbose Windows_NT 10.0.19045
67 verbose node v18.18.0
68 verbose npm  v9.8.1
69 error code CERT_HAS_EXPIRED
70 error errno CERT_HAS_EXPIRED
71 error request to https://registry.npm.taobao.org/pyright/-/pyright-1.1.347.tgz failed, reason: certificate has expired
72 verbose exit 1
73 timing npm Completed in 72563ms
74 verbose unfinished npm timer reify 1705916710441
75 verbose unfinished npm timer reify:unpack 1705916710501
76 verbose unfinished npm timer reifyNode:node_modules/pyright 1705916710503
77 verbose code 1
78 error A complete log of this run can be found in: C:\Users\admin\AppData\Local\npm-cache\_logs\2024-01-22T09_45_08_595Z-debug-0.log

**Comment by rchl** [comment]
It's a problem with the registry that you are using (`registry.npm.taobao.org`). As the error says, there is an issue with the certificate. Maybe it's an intermittent issue and it will fix itself later. Otherwise you might have to try different mirror if you can't use the official one. I suppose you have it overridden in `.npmrc` in your user directory.

**Comment by matresnan** [comment]
Run the following command to resolve the problem
`npm set strict-ssl false`
