### ISSUE TITLE
Type errors since recent update

### ISSUE THREAD

**Issue by thecircleisround** [sublimelsp/LSP-pyright#302]
I have been getting type errors since the most recent update using the following config: 

```
"python.analysis.diagnosticSeverityOverrides": {
			"reportDuplicateImport": "warning",
			"reportImplicitStringConcatenation": "warning",
			"reportMissingParameterType": "none",
			"reportUnboundVariable": "warning",
			"reportUninitializedInstanceVariable": "none",
			"reportUnusedClass": "information",
			"reportUnusedFunction": "information",
			"reportUnusedImport": "information",
			"reportUnusedVariable": "information",
			"reportGeneralTypeIssues": "none",

		},
```

I can disable each error individually but previously the `reportGeneralTypeIssues` option was enough

**Comment by jfcherng** [comment]
See release note: https://github.com/sublimelsp/LSP-pyright/releases/tag/1.2.71

**Comment by thecircleisround** [comment]
Got it. I noticed that and also thought the reportGeneralTypeIssues would still worked based on the docs.

**Comment by rchl** [comment]
As far as I understand it still exists and works, only that some of the issues it handled were split into its own settings.
