### ISSUE TITLE
not loading venv (poetry) 

### ISSUE THREAD

**Issue by mustafa0x** [sublimelsp/LSP-pyright#308]
```
LSP-pyright: INFO: poetry.lock detected. Run subprocess command: poetry env info -p
LSP-pyright: WARN: subprocess failed: 
LSP-pyright: INFO: Using python path "/usr/local/bin/python3"
```

This used to work, not sure what changed. I suspect that `poetry env info -p` is not run from the current directory.

```py
>>> import os; os.getcwd()
'/Applications/Sublime Text.app/Contents/MacOS'
```

Ok, it's not a CWD issue, since adding `-C :dir` didn't help. For some reason subprocess is failing. I tried the same command in a normal python repl and it worked fine.

```
$> /usr/bin/python3
Python 3.9.6
[Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.run('poetry env info -p -C :dir'.split())
/Users/:user/Library/Caches/pypoetry/virtualenvs/app-F-py3.12
```

**Comment by jfcherng** [comment]
Potentially this https://github.com/sublimelsp/LSP-pyright/commit/3b6140eaa12913940bf10b5e2253d4afccdd28e8 but that has been like 3 months ago already.

**Comment by mustafa0x** [comment]
In sublime console,

```
>>> print(subprocess.run('poetry -C :dir env info', shell=True, capture_output=True).stdout.decode())

Virtualenv
Python:         3.11.4
Implementation: CPython
Path:           NA
Executable:     NA

System
Platform:   darwin
OS:         posix
Python:     3.11.4
Path:       /usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11
Executable: /usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/bin/python3.11
```

If I add the `-p` flag then `returncode=1` and `stdout=''`. In either case, poetry is not seeing the environment. I'm not sure if it's due to it using homebrew's python. It shouldn't be.

**Comment by mustafa0x** [comment]
Yes I believe there's a PATH issue. It's strange that it affects poetry. I'll continue to investigate.

**Comment by jfcherng** [comment]
> We use subprocess.run('poetry env info -p -C :dir', shell=True)

> Yes I believe there's a PATH issue. It's strange that it affects poetry. I'll continue to investigate.

I noticed that we didn't add `env=os.environ` in https://github.com/sublimelsp/LSP-pyright/blob/de805dd140bfdbefd82f2c428b9149c7623f633e/plugin.py#L241-L248 . @mustafa0x  Do you know how to add it on your machine for testing?

**Comment by mustafa0x** [comment]
That didn't help. =/

I confirmed that it registered the code change by tweaking the log message on line 256.

**Comment by mustafa0x** [comment]
LSP-pyright.sublime-settings
```py
{
  "settings": {
    "python.pythonPath": "/Users/:user/.local/share/mise/installs/python/3.12/bin/python"
  }
}
```

This helped, but `subproccess.run` still fails. I wonder if the fact that poetry is a symlink affects things.

```
$> stat /usr/local/bin/poetry
  File: /usr/local/bin/poetry -> /Users/:user/.local/share/mise/installs/poetry/latest/bin/poetry
```

**Comment by mustafa0x** [comment]
Ok, the symlink can't be the reason. This also fails,

`subprocess.run('/Users/:user/.local/share/mise/installs/poetry/latest/bin/poetry -C :dir env info', shell=True, capture_output=True).stdout.decode()`

**Comment by mustafa0x** [comment]
Ok, prepending `mise x -- ` works. Not sure what it changes.

`print(subprocess.run('mise x -- poetry -C :dir env info -p', shell=True, capture_output=True).stdout.decode()`

**Comment by jfcherng** [comment]
could you try modify the PATH in `~/.profile`?

**Comment by rchl** [comment]
On my you modify `.zprofile` and it's only necessary to restart ST (not the system).

More info at https://lsp.sublimetext.io/troubleshooting/#updating-the-path-used-by-lsp-servers

**Comment by mustafa0x** [comment]
Yes, modifying PATH fixes. In the sublime console I entered:
```
import os
os.environ['PATH'] = '/Users/:user/.local/share/mise/shims:' + os.environ['PATH']

subprocess.run('poetry -C :dir env info', shell=True, capture_output=True, env=os.environ).stdout
```
Output:
```
Virtualenv
Python:         3.12.1
Implementation: CPython
Path:           /Users/:user/Library/Caches/pypoetry/virtualenvs/:app-py3.12
Executable:     /Users/:user/Library/Caches/pypoetry/virtualenvs/:app-py3.12/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.12.1
Path:       /Users/:user/.local/share/mise/installs/python/3.12.1
Executable: /Users/:user/.local/share/mise/installs/python/3.12.1/bin/python3.12
```

I'll add that PATH entry in `~/.bash_profile`.

**Comment by rchl** [comment]
I told you that you are supposed to modify (or create if it doesn't exist) `.zprofile` if you are using default shell which is zsh.

ST loads variables on start using `/bin/zsh -l`. You can see a line like that in ST console when it's starting.

**Comment by jfcherng** [comment]
Closed as resolved.
