### ISSUE TITLE
How to add the current project path to "python.analysis.extraPaths", currently using version 1.3.1

### ISSUE THREAD

**Issue by maryjeck** [sublimelsp/LSP-pyright#324]
before the version 1.3.1,it's auto include it

**Comment by jfcherng** [comment]
We do have some logic for `python.analysis.extraPaths` but I don't think we have ever include the current project path. What we do for it is find a venv for it.

**Comment by jfcherng** [comment]
Since your description is pretty specific, how do you know LSP-pyright adds current project path to `python.analysis.extraPaths`?

**Comment by jfcherng** [comment]
Didn't see `path` in pyright's recent changelog either 🤔

**Comment by maryjeck** [comment]
In the previous version, my custom module could be imported normally, but in this latest version, my project's custom module cannot be recognized.

**Comment by jfcherng** [comment]
> In the previous version, my custom module could be imported normally, but in this latest version, my project's custom module cannot be recognized. So I want to ask if there is any special parameter indicating the current project path

Could you provide a minimal reproducer repository (or uploading a `.zip` file) for test?

**Comment by maryjeck** [comment]
> > In the previous version, my custom module could be imported normally, but in this latest version, my project's custom module cannot be recognized. So I want to ask if there is any special parameter indicating the current project path在以前的版本中，我的自定义模块可以正常导入，但在这个最新版本中，我无法识别我的项目的自定义模块。所以我想问一下是否有任何特殊参数指示当前项目路径
> 
> Could you provide a minimal reproducer repository (or uploading a `.zip` file) for test?你能提供一个最小的复制器存储库（或上传 `.zip` 文件）进行测试吗？

ok,I'll pack it up

**Comment by maryjeck** [comment]
[test.zip](https://github.com/sublimelsp/LSP-pyright/files/15145162/test.zip)
This is a test file

![图片](https://github.com/sublimelsp/LSP-pyright/assets/4252556/8192467f-b85e-4ab1-907c-2c9662e1c510)
显示这个错误

**Comment by maryjeck** [comment]
It will be recognized in previous versions

**Comment by jfcherng** [comment]
> [test.zip](https://github.com/sublimelsp/LSP-pyright/files/15145162/test.zip) This is a test file

Thanks. I will test this when I go home.

**Comment by jfcherng** [comment]
![image](https://github.com/sublimelsp/LSP-pyright/assets/6594915/a7de8f2d-89e0-4fb9-a16b-1e909277b997)

I am not able to reproduce this with the latest released LSP-pyright. Could you share your LSP-pyright's settings?

**Comment by maryjeck** [comment]
// Settings in here override those in "LSP-pyright/LSP-pyright.sublime-settings"
{
    "settings": {
        "python.analysis.extraPaths": [
            "F:\\miniconda3\\Lib",
            "F:\\miniconda3\\Lib\\site-packages",
            "./",
            "workspace"
        ],
        "python.analysis.autoSearchPaths": true,
        "python.analysis.stubPath": "./typings",
        "python.analysis.diagnosticMode": "workspace",
        "python.analysis.diagnosticSeverityOverrides": {
            "reportUnboundVariable": "none",
            "reportGeneralTypeIssues": "information",
            "reportOptionalMemberAccess": "none",
            "reportUnusedImport": "warning"
        },
        "python.analysis.typeshedPaths": [
            "."
        ],
        "python.analysis.typeCheckingMode": "off",
        "pyright.disableOrganizeImports": true,
        "python.pythonPath": "F:\\miniconda3\\python.exe",
        "python.venvPath": ".",
    }
}

**Comment by maryjeck** [comment]
![图片](https://github.com/sublimelsp/LSP-pyright/assets/4252556/17b18dc9-5ba0-4c64-974a-3242fc12ccb6)
here

**Comment by jfcherng** [comment]
Still can't reproduce, even with the exact plugin settings.

![image](https://github.com/sublimelsp/LSP-pyright/assets/6594915/022a6390-bc74-4f35-bd40-c64dce38c1ba)

**Comment by jfcherng** [comment]
Someone probably has the same issue: https://github.com/microsoft/pyright/issues/7016#issuecomment-2042476674

**Comment by maryjeck** [comment]
> > Could your issue be reproduced in Sublime Text's safe mode without changing any LSP-pyright's settings?是否可以在不更改任何 LSP-pyright 设置的情况下在 Sublime Text 的安全模式下重现您的问题？
> 
> This hasn't been answered yet.这个问题还没有得到回答。

In safe mode, only set "python.pythonPath", the situation is still the same

**Comment by maryjeck** [comment]
> Someone probably has the same issue: [microsoft/pyright#7016 (comment)](https://github.com/microsoft/pyright/issues/7016#issuecomment-2042476674) But it's claimed fixed in pyright 1.1.360, which is LSP-pyright 1.3.1 🤔
What I use is  LSP-pyright 1.3.1

**Comment by maryjeck** [comment]
@jfcherng How to roll back to the previous version or a specific version

**Comment by jfcherng** [comment]
> @jfcherng How to roll back to the previous version or a specific version

I guess basically you want Package Control to not manage it.

```
	"unmanaged_packages_ignore": [],
```

**Comment by maryjeck** [comment]
The status of version 1.3.2 is the same, and the reconfiguration is also the same, o(╥﹏╥)o

**Comment by jfcherng** [comment]
Have you found a working old version yet?

**Comment by maryjeck** [comment]
I don’t know how to roll back. After setting it up according to your method, it didn’t roll back to the previous version.

**Comment by jfcherng** [comment]
> I don’t know how to roll back. After setting it up according to your method, it didn’t roll back to the previous version.

It prevents package control from updating. It won't do rollback. It's you have to do the rollback.

**Comment by jfcherng** [comment]
> I don’t know how to roll back.

1. Download the version you want. E.g., https://github.com/sublimelsp/LSP-pyright/archive/refs/tags/1.3.2.zip
2. Decompress and put it like

```
Packages/
└── LSP-pyright/
    ├── commands.py
    ├── dependencies.json
    ├── language-server
    │   ├── package.json
    │   └── package-lock.json
    ├── LICENSE
    ├── LSP-pyright.sublime-commands
    ├── LSP-pyright.sublime-settings
    ├── Main.sublime-menu
    ├── messages
    │   └── 1.1.68.md
    ├── messages.json
    ├── plugin.py
    ├── pyproject.toml
    ├── README.md
    ├── requirements.txt
    ├── resources
    │   └── typings
    │       └── sublime_text
    │           ├── _sublime_types.pyi
    │           ├── sublime.pyi
    │           └── sublime_plugin.pyi
    ├── sublime-package.json
    └── syntaxes
        ├── pyright.sublime-syntax
        ├── Python.sublime-syntax
        └── syntax_test.pyright-syntax-test
```

3. Restart ST.

**Comment by maryjeck** [comment]
![图片](https://github.com/sublimelsp/LSP-pyright/assets/4252556/c726da46-332d-4d5f-a455-adc7913f0230)
This version works very well, and can be retired as long as the upstream version is not resolved.

**Comment by maryjeck** [comment]
Say something else
![图片](https://github.com/sublimelsp/LSP-pyright/assets/4252556/fa5840d4-8215-4189-9f25-a7a8c72687e5)
Except for one package, lsp-basedpyright is also limited to this version. Is it because lsp is not set up properly or is it an upstream problem?

**Comment by jfcherng** [comment]
Just to confirm. LSP-pyright `1.3.0` and LSP `LSP-basedpyright` both works for you and their next version failed, right?

**Comment by maryjeck** [comment]
> Just to confirm. `LSP-pyright` `1.3.0` and LSP `LSP-basedpyright` `1.1.0` both work for you and their next version failed, right?

yes。The latter two versions of these two plug-ins do not work normal, whether it is a clean system or a safe mode

**Comment by maryjeck** [comment]
> LSP-basedpyright

By the way, I replaced package.json and package-lock.json in LSP-basedpyright 1.1.0 with the same files in 1.1.2, and the result is that it runs perfectly. It seems that it is not an upstream problem. Please help to see if there is a setting problem

**Comment by jfcherng** [comment]
Could you try this branch? https://github.com/sublimelsp/LSP-pyright/archive/refs/heads/fix/import-not-found.zip

**Comment by maryjeck** [comment]
> Could you try this: https://github.com/sublimelsp/LSP-pyright/archive/refs/heads/fix/import-not-found.zip
> 
> I doubt it may be fixed by [273a22c](https://github.com/sublimelsp/LSP-pyright/commit/273a22c3c97ef7eb87c15e9e95a061b5d084c8e6). This is the only behavior change that I notice between v1.3.0 and v1.3.1: [1.3.0...1.3.1](https://github.com/sublimelsp/LSP-pyright/compare/1.3.0...1.3.1)

sorry,Still not working

**Comment by jfcherng** [comment]
Unfortunately, I still can't spot other behavior different between [1.3.0...1.3.1](https://github.com/sublimelsp/LSP-pyright/compare/1.3.0...1.3.1).

**Comment by jfcherng** [comment]
Could you provide LSP-pyright's initialization logs for both v1.3.0 and v1.3.1 on your side?

**Comment by maryjeck** [comment]
> log panel

How to view lsp logs?
![image](https://github.com/sublimelsp/LSP-pyright/assets/4252556/1e57cb64-3374-4bb0-92b9-e51900fb0560)

Like this?

**Comment by jfcherng** [comment]
> > log panel
> 
> How to view lsp logs? ![image](https://private-user-images.githubusercontent.com/4252556/329097936-1e57cb64-3374-4bb0-92b9-e51900fb0560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMTg5OTgsIm5iZiI6MTcxNTIxODY5OCwicGF0aCI6Ii80MjUyNTU2LzMyOTA5NzkzNi0xZTU3Y2I2NC0zMzc0LTRiYjAtOTJiOS1lNTE5MDBmYjA1NjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDlUMDEzODE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTI0MDY0YjEyMDc0ZjFmMGVkNjJjOTY4MTc1MjkyM2ExYjhlNDVhMDg4NGEyNmU3YmM4Yjc1OTk4NjZlMjE1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.E6NpTQSqjDV6mNuiUgTxSkRKpvDnf2LeQzfBWt5Tpho)
> 
> Like this?

yes, but screenshot won't help.

**Comment by maryjeck** [comment]
I will create a new clean version and send it to you.

**Comment by jfcherng** [comment]
> I will create a new clean version and send it to you.

Appreciated.

**Comment by maryjeck** [comment]
[lsp-pyright-logs.zip](https://github.com/sublimelsp/LSP-pyright/files/15343358/lsp-pyright-logs.zip)
Sorry, I've been away on a business trip recently and haven't had the time to test it. I'm uploading it for you now.

**Comment by jfcherng** [comment]
> I have determined that in my case, it is a problem with the upstream language-server. I still use 1.3.0

You mean this is an `pyright` issue rather than `lsp-pyright`'s?

**Comment by maryjeck** [comment]
[diff.zip](https://github.com/sublimelsp/LSP-pyright/files/15359176/diff.zip)
This is the log for 1.10 and 1.15.

**Comment by jfcherng** [comment]
## OK (1.10)

```
'diagnosticMode': 'workspace', 'extraPaths': ['F:\\miniconda3\\Lib', 'F:\\miniconda3\\Lib\\site-packages', '.\\', './', '', '.'],
```

## FAILED (1.15)

```
'diagnosticMode': 'openFilesOnly', 'extraPaths': [],
```

---

I think they have some fundamental difference so that I don't think the v1.15 log is run under the same setup.

**Comment by jfcherng** [comment]
You may want to try whether your issue still persist in recent releases.

**Comment by maryjeck** [comment]
> You may want to try whether your issue still persists in recent releases.

I am now using lsp-based Pyright, and I find it quite useful. 😀

**Comment by jfcherng** [comment]
okay
