### ISSUE TITLE
How to make stdlib stubs work within a virtualenv

### ISSUE THREAD

**Issue by mikez** [sublimelsp/LSP-pyright#325]
_(Discussion moved from [here](https://github.com/sublimelsp/LSP/issues/2463).)_

**Aim**: show `lsp_hover` docstrings for both pip-installed modules and stdlibs.
To achieve the latter, I made pyi-stubs. This works. 👌

However, once I switch to a virtual environment, that is, provide the `venvPath` and `venv` options in pyrightconfig.json, then the stdlib docstrings disappear. Everything else works: the packages installed in the virtual environment show their docstrings, as do the custom editable installs I put in the `extraPaths` (pyright doesn't seem to pick those up natively otherwise). It is only the pyi-stubs of the stdlib which don't show up.

- See: [pyrightconfig.json](https://gist.github.com/mikez/ca25f4a62c040eb8037a7d80588dc954) and [LSP-pyright.sublime-settings ](https://gist.github.com/mikez/e66bacecc43402d141d2bae84022d43e).

**Comment by mikez** [comment]
BTW: If there are ways in which I can easily debug and troubleshoot this myself, I'm happy to do so. Still a newcomer to this project and not quite sure where to start.

**Comment by jfcherng** [comment]
It seems that pyright prefers its own typeshed stubs for stdlib but I am not sure. Set `python.analysis.logLevel` to `Trace` will provide more information for debugging. But since I don't know what's the expected output, I can't interpret them.

One thing works on my test is put stdlib stubs into `typings/` under project root, but we don't want to do that for every project for sure...

One person may have a same issue: https://github.com/microsoft/pyright/issues/7016#issuecomment-2042476674

**Comment by mikez** [comment]
@jfcherng `python.analysis.logLevel` in the `LSP-pyright.sublime-settings`: should I see this output under "LSP: Toggle Log Panel" or elsewhere?
I don't see any difference right now between "Information" and "Trace" in that Log Panel output.

**Comment by jfcherng** [comment]
> @jfcherng `python.analysis.logLevel` in the `LSP-pyright.sublime-settings`: should I see this output under "LSP: Toggle Log Panel" or elsewhere? I don't see any difference right now between "Information" and "Trace" in that Log Panel output.

either in the panel or the console.

**Comment by mikez** [comment]
I looked into the logs. It seems in **all** cases this directory is loaded

   ~/Library/Caches/Sublime Text/Package Storage/LSP-pyright/21.7.1/language-server/node_modules/pyright/dist/typeshed-fallback/stdlib

and the custom `stdlib-pyi` directory is listed as part of the extraPaths in the logs but then **not** considered.

1. When I have `venv` enabled, then it ignores the docstrings of built-ins all-together, including `os` and `json` which have docstrings as shipped with Python. ❌
2. When I **don't** have `venv` enabled, then it reads the docstrings from the source (e.g. `os.py` and `json/__init__.py`) where its present ✅; and where not (e.g. `str.strip`) it shows no docstrings. ❌
3. When I manually edit `~/Library/Caches/Sublime Text/Package Storage/LSP-pyright/21.7.1/language-server/node_modules/pyright/dist/typeshed-fallback/stdlib/builtins.pyi` and add docstrings to `strip`, then it shows up correctly. ✅

So the only very hacky solution I can think of right now is to overwrite `… /typeshed-fallback/stdlib/builtins.pyi` and the like with versions with docstrings; it seems there must be a better way?

**Comment by jfcherng** [comment]
OK. I see that, for Pylance, it puts users' `extraPaths` before bundled typeshed, so user's stdlib stubs works... while in Pyright, the bundled typeshed always is the first.

```
  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892) Search paths for file:///d%3A/Repo/ST-AutoSetSyntax'}
:: [20:20:31.195] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Users\\jfcherng\\AppData\\Local\\Sublime Text\\Package Storage\\LSP-pylance\\ms-python.vscode-pylance~2024.4.105\\extension\\dist\\typeshed-fallback\\stdlib'}
:: [20:20:31.195] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   d:\\Repo\\ST-AutoSetSyntax'}
:: [20:20:31.195] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   D:\\Repo\\ST-AutoSetSyntax\\stubs'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   d:\\Repo\\ST-AutoSetSyntax\\typings'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   C:\\Users\\jfcherng\\AppData\\Roaming\\Sublime Text\\stubs'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Users\\jfcherng\\AppData\\Roaming\\Sublime Text\\typings'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Users\\jfcherng\\AppData\\Local\\Sublime Text\\Package Storage\\LSP-pylance\\resources\\typings\\stdlib'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Users\\jfcherng\\AppData\\Local\\Sublime Text\\Package Storage\\LSP-pylance\\ms-python.vscode-pylance~2024.4.105\\resources\\typings\\sublime_text'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Users\\jfcherng\\AppData\\Local\\Sublime Text\\Package Storage\\AutoSetSyntax\\libs-py38@windows_x64'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Program Files\\Sublime Text\\Lib\\python38'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Program Files\\Sublime Text\\Lib\\python3'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Users\\jfcherng\\AppData\\Roaming\\Sublime Text\\Lib\\python38'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Program Files\\Sublime Text\\Packages'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Users\\jfcherng\\AppData\\Roaming\\Sublime Text\\Packages'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   d:\\Repo\\ST-AutoSetSyntax\\typings'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Users\\jfcherng\\AppData\\Local\\Sublime Text\\Package Storage\\LSP-pylance\\ms-python.vscode-pylance~2024.4.105\\extension\\dist\\typeshed-fallback\\stubs\\...'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Users\\jfcherng\\AppData\\Local\\Sublime Text\\Package Storage\\LSP-pylance\\ms-python.vscode-pylance~2024.4.105\\extension\\dist\\bundled\\stubs'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Users\\jfcherng\\AppData\\Local\\Programs\\Python\\Python312\\DLLs'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Users\\jfcherng\\AppData\\Local\\Programs\\Python\\Python312\\Lib'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   c:\\Users\\jfcherng\\AppData\\Local\\Programs\\Python\\Python312'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   d:\\Repo\\ST-AutoSetSyntax\\.venv'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892)   d:\\Repo\\ST-AutoSetSyntax\\.venv\\Lib\\site-packages'}
:: [20:20:31.196] <-  LSP-pylance window/logMessage: {'type': 3, 'message': '(34892) Adding fs watcher for library directories:\n file:///c%3A/Users/jfcherng/AppData/Local/Programs/Python/Python312/DLLs\nfile:///c%3A/Users/jfcherng/AppData/Local/Programs/Python/Python312/Lib\nfile:///c%3A/Users/jfcherng/AppData/Local/Programs/Python/Python312\nfile:///d%3A/Repo/ST-AutoSetSyntax/.venv\nfile:///d%3A/Repo/ST-AutoSetSyntax/.venv/Lib/site-packages'}
```

**Comment by jfcherng** [comment]
Pylance auto puts `extension/dist/typeshed-fallback/stdlib` as the first in the final `extraPaths` as well, but it seems to combine the bundled's typeshed's results with users' while Pyright's just stop there probably.

**Comment by jfcherng** [comment]
I may just suggest to ask the pyright official: I have a custom stdlib stubs with docstrings (but it doesn't have type annotation unfortunately). How to use it with the builtin stdlib typeshed-fallback?

**Comment by jfcherng** [comment]
A finding is that, by revise the extension of our stdlib stubs from `.pyi` to `.py`, Pyright seems to consider they are source codes with docstrings and adds typeshed's type annotations to it and resulting in a perfect output.

[stdlib-win64.zip](https://github.com/sublimelsp/LSP-pyright/files/15164033/stdlib.zip)

**Comment by mikez** [comment]
Thanks @jfcherng. I opened [a discussion](https://github.com/microsoft/pyright/discussions/7807) at pyright. It seems to me, pyright should consider including native support for builtin docstrings as manual generation seems somewhat difficult to maintain.

**Comment by jfcherng** [comment]
I think https://github.com/sublimelsp/LSP-pyright/issues/325#issuecomment-2085239473 is 99% perfect, unless you want to see stdlib's real source codes.
