### ISSUE TITLE
Disable in REPL output?

### ISSUE THREAD

**Issue by Gabriel-p** [sublimelsp/LSP-pyright#343]
I use the SublimeREPL package to run code in a tab and pyright checks every line of the output, finding of course dozens of errors. How can I disable the checking at the REPL output?

**Comment by jfcherng** [comment]
what's the output in the popup of `ctrl+shift+alt+p` in REPL?

**Comment by jfcherng** [comment]
Should have been fixed in v1.4.8 by https://github.com/sublimelsp/LSP-pyright/commit/0a326142683339ba813d8d23a4d2cf8fa28db0fa
