### ISSUE TITLE
Conda environment is not recognized

### ISSUE THREAD

**Issue by wigging** [sublimelsp/LSP-pyright#348]
The LSP-pyright package isn't finding my conda environment. But it seems to be working with a Python virtual environment. I'm using the following configuration:
- macOS Sonoma 14.6.1
- Sublime Text Build 4180
- conda 24.7.1
- LSP-pyright 1.4.12
- Python 3.12.4

## Working with Python venv

I created and activated a Python virtual environment, installed NumPy, then opened Sublime Text as shown below:

```text
python -m venv .venv
source .venv/bin/activate
pip install numpy
subl .
```

I have a simple example of using NumPy:

```python
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)
```

Everything works fine and LSP-pyright finds the venv environment as shown in the status bar:

<img width="534" alt="pyright-status-venv" src="https://github.com/user-attachments/assets/47745d18-5be3-43ba-80e7-8b5d48b73242">

## Not working with conda

I created and activated a Python conda environment with NumPy installed and opened Sublime Text using:

```text
conda create --name envnumpy python numpy
conda activate envnumpy
subl .
```

I have a simple example of using NumPy:

```python
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)
```

I can run the example without any problems but LSP-pyright is not able to resolve the NumPy source as shown below. This does not happen when I use a Python virtual environment.

<img width="622" alt="pyright-conda-resolve" src="https://github.com/user-attachments/assets/e1fa52a6-498b-47c2-afcd-dc261e7870db">

I am also not seeing anything regarding the conda environment in the LSP-pyright status bar:

<img width="306" alt="pyright-status-conda" src="https://github.com/user-attachments/assets/886b1945-3b97-4e1f-ba47-164735e323de">

**Comment by jfcherng** [comment]
When 
```bash
conda create --name envnumpy python numpy
conda activate envnumpy
subl .
```
What's the output of import `os; os.environ.get('CONDA_PREFIX')` in ST console?

**Comment by wigging** [comment]
It returns the path to the conda environment. See the screenshot below.

<img width="374" alt="condaprefix" src="https://github.com/user-attachments/assets/91cbefc4-93ac-49fe-8d80-4d2de1219c22">

**Comment by jfcherng** [comment]
The issue is that I check for `VENV_DIR/pyvenv.cfg` to validate whether a directory (in this case, `$CONDA_PREFIX`) is a venv or not. But somehow `$CONDA_PREFIX/pyvenv.cfg` doesn't exist.

**Comment by wigging** [comment]
Why do you need to find `pyvenv.cfg`? If you activate a conda environment, then do `echo $CONDA_PREFIX`, it will return the path to the activated conda environment. If you are not in an active conda environment and do `echo $CONDA_PREFIX`, then it will not return anything. Seems like that should be enough to determine if a conda environment is active and where the environment is located.

**Comment by jfcherng** [comment]
> Why do you need to find pyvenv.cfg? 

Because I need these information. Ideally, without invoking a process.
![image](https://github.com/user-attachments/assets/b6e970c5-4e81-4342-a896-83ac302f40f0)

**Comment by wigging** [comment]
You can get the name of the conda environment from the path without having to use `pyvenv.cfg`.

**Comment by wigging** [comment]
Using just Python, this gets the name of the activated conda environment:
```python
import os
os.getenv("CONDA_DEFAULT_ENV")
```
And this gets the path to the activated conda environment:
```python
import os
os.getenv("CONDA_PREFIX")
```

**Comment by wigging** [comment]
You can use this to get the Python version of the activated conda environment:
```python
from platform import python_version
python_version()
```

**Comment by jfcherng** [comment]
Thanks. But the issue is not I don't know how to get those. Refactoring is required.

**Comment by jfcherng** [comment]
Could you try this PR: https://github.com/sublimelsp/LSP-pyright/pull/349

**Comment by wigging** [comment]
The `Browse Packages...` in Sublime Text just shows the sublime-settings files for packages that I have installed. Where are the files located for the LSP-pyright package?

**Comment by wigging** [comment]
I copied your changes in the `fix/venv-conda` and put them in the `~/Library/Application Support/Sublime Text/Packages/LSP-pyright` directory. The directory tree is shown below. These changes seem to fix the problems I had with conda environments on macOS. Thank you.

```text
LSP-pyright
└── plugin
    ├── client.py
    ├── utils.py
    └── virtual_env
        ├── __init__.py
        ├── helpers.py
        ├── venv_finder.py
        └── venv_info.py
```

**Comment by jfcherng** [comment]
I have made a new release 1.4.13, which should be available on Package Control within hours. You can remove those override when it comes.
