### ISSUE TITLE
Single file mode no longer working

### ISSUE THREAD

**Issue by jwortmann** [sublimelsp/LSP-pyright#359]
This might be an upstream issue in Pyright, but I'd like to report it here first to see if others are experiencing the same or if there maybe is a workaround.

Since the last update or one of the last updates, the server is more or less non-functional if a file was opened in single file mode, i.e. with no folders in the sidebar. Instead, it constantly asks for `workspace/configuration` and logs

> File or directory "\\\<default workspace root>" does not exist.

to the status bar.

If there are no workspace folders, LSP sends
```
'rootUri': None, 'rootPath': None, 'workspaceFolders': None,
```
as part of the [InitializeParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeParams), but this should be fine according to the specs. It seems like the server can't handle this anymore?

**Comment by jfcherng** [comment]
yeah the auto completion seems not working when single file mode

**Comment by jwortmann** [comment]
I created an upstream issue report https://github.com/microsoft/pyright/issues/8919

**Comment by jfcherng** [comment]
Should be fixed by https://github.com/sublimelsp/LSP-pyright/releases/tag/1.4.22 as per upstream's claim.
