### ISSUE TITLE
Replace activity monitor with something that doesn't spawn a thread

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-pyright#36]
I'm noticing some stuttering now when editing files that causes pyright to emit its "analyzing files" notification. It would be nice if this stuttering was not present. Can we perhaps create our own activity monitor? Or communicate with the sublime_lib maintainers to have an option to run the callbacks on the main thread instead of spawning another thread?

**Comment by rchl** [comment]
I've made https://github.com/sublimelsp/lsp_utils/pull/47 but it might be a good idea to ask sublime_lib to do it instead.
