### ISSUE TITLE
Sublime Imports can not be resolved

### ISSUE THREAD

**Issue by LDAP** [sublimelsp/LSP-pyright#37]
Although dev_environment is set to sublime_text, module imports can not be resolved.

**Reproduce:**
1. Install LSP, LSP-pyright
2. LSP-pyright settings:
```json
// Settings in here override those in "LSP-pyright/LSP-pyright.sublime-settings"
{
    "dev_environment": "sublime_text",
}
```
3. Create a plugin.py and import `sublime`

**This happens:**
![grafik](https://user-images.githubusercontent.com/8215084/101458316-041e2100-3937-11eb-942d-ccae9282b3fb.png)
(On loading the plugin the status message is shown just fine)

[pyright.log](https://github.com/sublimelsp/LSP-pyright/files/5657857/pyright.log)

**Expected:**
I would instead expect the import to be resolved. (Question: Should other imports like from LSP.plugin be resolved too, or are stubs necessary in this case?)

**Environment**

Windows 10, Anaconda 4.9.0 installed
Sublime Text 4094
LSP 1.2.3, LSP-pyright 1.1.12

```
Python 3.3>>> sys.path
['C:\\Program Files\\Sublime Text\\Lib\\python3.3.zip', 'C:\\Program Files\\Sublime Text\\Lib\\python33', 'C:\\Program Files\\Sublime Text\\Lib\\python3', 'C:\\Users\\Lucas Alber\\AppData\\Roaming\\Sublime Text\\Lib\\python33', 'C:\\Users\\Lucas Alber\\AppData\\Roaming\\Sublime Text\\Packages', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\pygments\\all', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\SUBLIM~1\\st3', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\LSP_UT~1\\st3', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\wcwidth\\all', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\pywinpty\\ST3_WI~2', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\backrefs\\st3', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\bracex\\st3', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\MARKUP~1\\all', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\pymdownx\\st3', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\pyte\\all', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\PYTHON~1\\st3', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\pyyaml\\st3', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\requests\\all', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\PYTHON~2\\all', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\JSONSC~1\\all', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\mdpopups\\st3', 'C:\\Users\\LUCASA~1\\AppData\\Roaming\\SUBLIM~1\\Packages\\wcmatch\\st3']

Python 3.8 >>> sys.path
['C:\\Program Files\\Sublime Text\\Lib\\python3.8.zip', 'C:\\Program Files\\Sublime Text\\Lib\\python38', 'C:\\Program Files\\Sublime Text\\Lib\\python3', 'C:\\Users\\Lucas Alber\\AppData\\Roaming\\Sublime Text\\Lib\\python38', 'C:\\Users\\Lucas Alber\\AppData\\Roaming\\Sublime Text\\Packages']
```

**Comment by jfcherng** [comment]
The log LGTM since `C:\\Program Files\\Sublime Text\\Lib\\python33` is included in the `extraPaths`. Are you using a project/folder? Single file won't work well with LSP.

**Comment by LDAP** [comment]
I did not. When using a folder `sublime` gets resolved. The LSP imports do not.

**Comment by jfcherng** [comment]
> Question: Should other imports like from LSP.plugin be resolved too, or are stubs necessary in this case?

I have another `LSP` as a submodule in my Data directory like https://github.com/jfcherng-sublime/ST-my-settings/tree/16029056638f8cb916b6ada02af9b386423dec91/typings. And add `Data/typings/` into `extraPaths` like https://github.com/jfcherng-sublime/ST-my-settings/blob/16029056638f8cb916b6ada02af9b386423dec91/Packages/User/LSP-pyright.sublime-settings#L34.

**Comment by LDAP** [comment]
Unreladed to this I asked if it is possible to force Package Control to unpack the packages. Until now, its not. But this may be a good reason to implement such a feature.

**Comment by jfcherng** [comment]
If you directly clone the st4000-exploration branch into `Packages/`, if probably will auto update.

**Comment by LDAP** [comment]
Might be worth a try. Adding the sublime-packages to path does not work?

**Comment by jfcherng** [comment]
> Might be worth a try. Adding the sublime-packages to path does not work?

no.
