### ISSUE TITLE
venv detection slows down initialization

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-pyright#370]
The sync venv detection logic delays initialization quite a bit in my LSP "monorepo":

https://github.com/user-attachments/assets/a877c681-b61f-4d9e-bd2d-1f7610e0b53a

Not saying it needs to be fixed because it can be easily worked around (disable or customize the logic in project settings) but maybe there is something that can be improved here for general case.

(same applies to LSP-basedpyright)

**Comment by jfcherng** [comment]
Does the latest master branch commit works for your case? https://github.com/sublimelsp/LSP-pyright/commit/239369dcdca5963eed0336d9a92e37d550ad8c64

**Comment by rchl** [comment]
Yes, it works. Thanks.
