### ISSUE TITLE
Blender's extra paths are not loaded correctly

### ISSUE THREAD

**Issue by Martysh12** [sublimelsp/LSP-pyright#377]
When I set the development environment to `blender`, this is what is outputted in the console:
```
[LSP-pyright][ERROR] Failed to update extra paths for dev environment "blender": Failed to parse JSON: Extra data: line 2 column 1056 (char 1056)
```
-----
I tried to run the command LSP-pyright uses to find the paths manually (e.g `blender --background --python .\print_sys_path.py`), with `print_sys_paths.py` containing this script:
https://github.com/sublimelsp/LSP-pyright/blob/32ec33fc4c6cd890a9102419cb3f5ed908e8252a/plugin/dev_environment/impl/blender.py#L23-L26

The following is outputted:
```
Blender 4.3.2 (hash 32f5fdce0a0a built 2024-12-17 03:35:23)
Hello, world!
INFO: Ucupaint 2.1.4 is registered!
INFO: Ucupaint update routine is done in 0.00 ms!
{"executable": "E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\python\\bin\\python.exe", "paths": ["E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\scripts\\startup", "E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\scripts\\modules", "E:\\SteamLibrary\\steamapps\\common\\Blender\\python311.zip", "E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\python\\DLLs", "E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\python\\Lib", "E:\\SteamLibrary\\steamapps\\common\\Blender", "E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\python", "E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\python\\Lib\\site-packages", "E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\scripts\\freestyle\\modules", "C:\\Users\\Martin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.3\\scripts\\addons\\modules", "E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\scripts\\addons_core", "C:\\Users\\Martin\\AppData\\Roaming\\Blender Foundation\\Blender\\4.3\\scripts\\addons", "E:\\SteamLibrary\\steamapps\\common\\Blender\\4.3\\scripts\\startup\\bl_ui"]}Goodbye, world!
INFO: Ucupaint 2.1.4 is unregistered!
```
-----
I feel like it would be smarter to write a JSON file containing the paths to a temporary directory, which is already created (see below), and read it from there.
https://github.com/sublimelsp/LSP-pyright/blob/32ec33fc4c6cd890a9102419cb3f5ed908e8252a/plugin/dev_environment/impl/blender.py#L19

So, Blender should be executed in the temporary directory, and the Blender script should be changed to something along the lines of:
```py
import bpy
import json
import sys

with open("paths.json", "w") as f:
    json.dump({"executable": sys.executable, "paths": sys.path}, f)

bpy.ops.wm.quit_blender()
```
Much less hackier.

**Comment by jfcherng** [comment]
@rwols what do you think?

I don't use Blender but my major doubt is that
> import bpy
will this work?

**Comment by Martysh12** [comment]
> > import bpy
> 
> will this work?

Yes, the script is executed inside of Blender, so it has access to Blender's API.

**Comment by jfcherng** [comment]
It seems that `import bpy` doesn't do anything meaningful there. The only required change is `with open("paths.json", "w") as f:`

**Comment by Martysh12** [comment]
> It seems that `import bpy` doesn't do anything meaningful there (`bpy.ops.wm.quit_blender()
> ` either). The only required change is `with open("paths.json", "w") as f:`. Is this correct?

Yes, I felt like including `bpy.ops.wm.quit_blender()` as it is the "official" way of quitting Blender, as opposed to doing `exit(0)`.

**Comment by jfcherng** [comment]
Hi @Martysh12 , are you able to try https://github.com/sublimelsp/LSP-pyright/issues/378 ?

**Comment by rwols** [comment]
I don't use blender every day but using `bpy.ops.wm.quit_blender()` seems good.

**Comment by rwols** [comment]
The error is due to the string "Goodbye, world!" printed after the json data. That doesn't happen in my version of blender. Anyway, it's indeed better to just dump the content to another file.
