### ISSUE TITLE
LSP-Pyright takes over status bar

### ISSUE THREAD

**Issue by Fingel** [sublimelsp/LSP-pyright#41]
Hi, 

Something in a recent update, (perhaps this project, e92d52f0f3548401c827f641b050528e10ef07db?) has caused the sublime status bar to show repeated "LSP-pyright: 1 file to analyze[=  ]". The position of the progress indicator is different in each label so my guess is the status line is being appended instead of replaced. There is no way to clear the status bar without restarting sublime text.
<img width="1375" alt="Screen Shot 2020-12-10 at 2 38 39 PM" src="https://user-images.githubusercontent.com/3046397/101838785-14c8c580-3af6-11eb-9085-0ae305204f71.png">

**Comment by rwols** [comment]
See: https://github.com/sublimelsp/lsp_utils/issues/48

**Comment by rchl** [comment]
Released fix in https://github.com/sublimelsp/lsp_utils/releases/tag/1.11.1
