### ISSUE TITLE
On Hover Doc String Formatting Lacks Linebreaks

### ISSUE THREAD

**Issue by maegul** [sublimelsp/LSP-pyright#42]
Not sure if this is a pyright or lsp issue (I'm new to this ecosystem).

Line breaks between parameters are not being printed in the hover over signature and docstring.

See screenshot below:

![image](https://user-images.githubusercontent.com/13930443/101879461-7b78dc80-3be5-11eb-9723-1d405f0fd740.png)

Line breaks between parameters are not printed.  Compare with the ipython output:

![image](https://user-images.githubusercontent.com/13930443/101879649-c72b8600-3be5-11eb-8405-3a774799a69a.png)

**Comment by jfcherng** [comment]
I think that's because we render it in Markdown format. However, a single `\n` is just like a whitespace while `\n\n` is a new line.

---

Wondering could we intercept messages in LSP-* before it gets rendered with mdpopup lib... I, privately, actually would like to change the output format of signature help for better syntax highlighting for it.

**Comment by rwols** [comment]
The pyright language server tells LSP that the content is `markdown`, so LSP renders it as markdown.

The fact that the content is not actually markdown, but numpy-flavored restructured text, is really a problem of pyright.

**Comment by rchl** [comment]
There is another aspect to it - the markdown implementation that is used.

Using github flavored implementation would preserve the single linebreaks too.

**Comment by rwols** [comment]
Fair point. I'll link this to https://github.com/facelessuser/sublime-markdown-popups/issues/103 and ping @facelessuser so we have another example where it would be beneficial to switch mdpopups to (GitHub-flavored) commonmark.

But I still think pyright should put in more effort to move from **numpy-flavored restructured text**-space to **commonmark**-space. It might accidentally render alright in VSCode, but the spaces are wrong.

For one thing pyright puts in no effort at all to fill in the parameter documentation. This is readily parseable information.

**Comment by facelessuser** [comment]
Have you compared the output in commonmark? I'm not sure it would render as expected there either.

**Comment by rchl** [comment]
I've only checked here in github but you are right that commonmakr also doesn't render the newline:

https://spec.commonmark.org/dingus/?text=(method)%20get_sheet_index%3A%20(self%3A%20Window%2C%20sheet%3A%20Sheet)%20-%3E%20Tuple%5Bint%2C%20int%5D%5Cn%60%60%60%5CnReturns%20the%20group%2C%20and%20index%20within%20the%20group%20of%20the%20%60sheet%60%0AReturns%20(-1%2C%20-1)%20if%20not%20found

**Comment by facelessuser** [comment]
That's what I figured. It doesn't look like it's formatted for Markdown at all.

**Comment by maegul** [comment]
Sorry for being new to the ecosystem.  

But yes, @rwols , from a quick search on the `pyright`/`pylance` repos, it does seem to be a problem on that side for which there are a few pre-existing issues, linked below for the curious ...

[microsoft/pyright#721](https://github.com/microsoft/pyright/issues/721)
[microsfot/pylance-release#41](https://github.com/microsoft/pylance-release/issues/41)
[microsoft/pylance-release#48](https://github.com/microsoft/pylance-release/issues/48)
[microsfot/pylance-release#476](https://github.com/microsoft/pylance-release/issues/476)

**Comment by rwols** [comment]
I'll close this because we're doing everything correctly here. pyright should have a transformation from whatever its documentation space is to markdown space. I understand that is not trivial because there are many different documentation-styles in Python, but that is a problem of pyright.

**Comment by maegul** [comment]
Seems that `pyright` might have fixed this on their end now (See https://github.com/microsoft/pyright/pull/1449)?

I noticed a change in the docstring formatting in sublime lsp-pyright after the latest `pyright` version was pulled into lsp-pyright (today or yesterday?).  But it still isn't right ... line breaks are not respected.

Not sure if everything is fixed on the pyright side ... but a quick comparison with `pylance` on VSCode shows that line breaks are rendered there now with nice docstring pop ups.  Don't know how much of this is pylance or pyright though.

**Comment by rchl** [comment]
Example response (identical in both ST and VSCode) where the line breaks are formatted correctly in VSCode but not in ST:

```json
{
  "contents": {
    "kind": "markdown",
    "value": "```python\n(function) open: (url: Text, new: int = ..., autoraise: bool = ...) -> bool\n```\nDisplay url using the default browser.\n\nIf possible, open url in a location determined by new.\n- 0: the same browser window (the default).\n- 1: a new browser window.\n- 2: a new browser page (\"tab\").\nIf possible, autoraise raises the window (the default) or not."
  },
  "range": {
    "end": {
      "character": 23,
      "line": 56
    },
    "start": {
      "character": 19,
      "line": 56
    }
  }
}
```

I believe it's again about differences with the markdown parser used.

ST:

![Screenshot 2021-02-08 at 11 27 07](https://user-images.githubusercontent.com/153197/107207435-96f33e80-6a00-11eb-8cc6-8f58f9d530b7.png)

VSCode:

![Screenshot 2021-02-08 at 11 28 18](https://user-images.githubusercontent.com/153197/107207577-bf7b3880-6a00-11eb-9a96-3f0244e87ea1.png)

**Comment by rwols** [comment]
Yes, python-markdown wants two newlines before starting an unordered list. In the sample payload, only one newline is used before starting an unordered list. So we're back at facelessuser/sublime-markdown-popups#103.

**Comment by rchl** [comment]
Also, I'm not sure if that issue is exactly what @maegul seen.

**Comment by maegul** [comment]
> Also, I'm not sure if that issue is exactly what @maegul seen.

Not *exactly* but it seems to be the same issue.  
I'm talking about numpy style docstrings (where the main issue is line breaks between individual parameters).

VS Code:

![image](https://user-images.githubusercontent.com/13930443/107246883-d4011480-6a84-11eb-8e6a-c85dbc9b8a5c.png)

ST:

![image](https://user-images.githubusercontent.com/13930443/107246973-ea0ed500-6a84-11eb-9fb4-c808bb668be9.png)

**Comment by rchl** [comment]
So it's still pretty much the same as in the initial comment then.

**Comment by rwols** [comment]
Not really, initially it was just restructured text, but now it's commonmark.

**Comment by maegul** [comment]
> So it's still pretty much the same as in the initial comment then.

Regarding line breaks ... yes

There is a slight difference in the output though ... indentation white space is preserved now but wasn't before (which is what prompted me to check for updates in pyright).  Don't know why though 🤷 (I'm not on top of the code base here ... just a nagging user 😏 )

**Comment by rwols** [comment]
https://github.com/sublimelsp/LSP/commit/111fac6ea125df35b7887cf252a6f2aa539ac1b2 should be an improvement :)

**Comment by maegul** [comment]
Nice!  Makes a world of difference!!
