### ISSUE TITLE
Cleanup plugin after updating pyright dep

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-pyright#47]
From https://github.com/microsoft/pyright/releases/tag/1.1.96:
- Behavior Change: Switched to LSP-native progress reporting rather than using custom progress reporting messages.
- New Feature: Added a new diagnostic rule called "reportInvalidTypeVarUse"

**Comment by jfcherng** [comment]
From https://github.com/microsoft/pyright/releases/tag/1.1.98:

New Feature: Added new diagnostic rule "reportUnusedCoroutine" that reports an error if the result returned by an async function is not consumed (awaited, assigned to a variable, etc.). This detects and reports a common error when using async coroutines.
