### ISSUE TITLE
Dubious prefixes in the LSP Hover content cause invalid syntax highlighting

### ISSUE THREAD

**Issue by frou** [sublimelsp/LSP-pyright#55]
<img width="467" alt="Screenshot 2021-02-21 at 13 06 27" src="https://user-images.githubusercontent.com/172663/108626035-0a0ba480-7446-11eb-8cdb-0bb597f43364.png">

e.g. `(class) ` here.

---

Maybe it's possible to configure `pyright` to not include these prefixes like `(variable)`, `(function)`, `(class)`, etc in the first place?

Even when they're not bright red because they're colliding with a language keyword, they remind me of the classic example of a pointless comment:

    // (increment x)
    x++

**Comment by jfcherng** [comment]
I don't think it can be changed in this repo but i will be glad if i am wrong.

**Comment by rchl** [comment]
You can read more about why pyright (or MS in general) is doing that in https://github.com/microsoft/pyright/issues/1030

**Comment by frou** [comment]
Damn, the _LSP-aka-VScode-monoculture_ trap strikes again

**Comment by rwols** [comment]
Somewhat related: https://github.com/microsoft/language-server-protocol/issues/1115

Although you could also argue that mdpopups should try to use "safe" highlighter contexts, instead of assuming all code snippets are correctly parseable.

**Comment by jfcherng** [comment]
There is nothing we can do in LSP-pyright, either way.
