### ISSUE TITLE
New option

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-pyright#57]
According to the latest changelog there is a new option so we should probably update the schema

> New Feature: Added "reportOverlappingOverload" diagnostic rule, splitting out a few checks that were previously in the "reportGeneralTypeIssue" rule. This allows for finer-grained control over these overload checks.

**Comment by jfcherng** [comment]
Done in https://github.com/sublimelsp/LSP-pyright/commit/74b4cc2cd0d73c209369422743ee2de0b9b2e87b
