### ISSUE TITLE
Support multi-root workspace venvs elegantly

### ISSUE THREAD

**Issue by asfaltboy** [sublimelsp/LSP-pyright#61]
Thanks for a great plugin 🙇  the work y'all are doing is legitimely excellent!

@rwols [said here][1] that multi-root workspace venv are supported inside workspace folders, but I don't really understand how it should work in Sublime (vs VSCode).

I'm dealing with a "mono-repo style project", where I have a venv per "service sub-dir" inside `src/`. I first looked into adding execution environments, but soon discovered `venv` is no longer supported within them ([see thread][2]).

I then tried setting up a separate `pyrightconfig.json` per service sub-directory, each having it's own `venv`; however, only the config file at the root of the project seems to be picked up by default.

Finally, I sort of managed to work around this by also adding a bunch of `folders` in my ST project config like so:
```
{
	"folders":
	[
		{
			"folder_exclude_patterns":
			[
				"node_modules"
			],
			"path": "my_project"
		},
		{ "path": "my_project/src/service1" },
		{ "path": "my_project/src/service2" },
		{ "path": "my_project/src/service3" },
		{ "path": "my_project/src/service4" },
		// few dozen more services
	],
}
```

But what I really want is to just see one folder (the root of `my_project`) in my folder side-bar, and have each venv be automatically picked up in the `src/` root.

Is there a better way to handle "monorepo folders", or are we stuck with this method now? Or, should I try to raise this issue in microsoft/pyright once more?

Alternatively, could we perhaps support this use case, by appending folders to the workspace that are marked by a custom setting, e.g `workspaceFolderRoot: src/`?

[1]: https://discordapp.com/channels/280102180189634562/645268178397560865/660605047440277583
[2]: https://github.com/microsoft/pyright/issues/1508#issuecomment-794734334

**Comment by jfcherng** [comment]
> Finally, I sort of managed to work around this by also adding a bunch of `folders` in my ST project config like so:

That looks like exactly the "multi-root" in VSCode.
https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by rchl** [comment]
If you'd like something like that to be supported you most likely would have to fight for it in https://github.com/microsoft/pylance-release/issues and if it would get implemented it would likely trickle down to pyright.

**Comment by sdemura** [comment]
VSCode supports monorepos with folder specific `pyrightconfig.json`. This _also_ works in vim/nvim with `coc-pyright`. What can be done to make sublime/lsp-pyright work the same?
