### ISSUE TITLE
How can I use custom stub files?

### ISSUE THREAD

**Issue by ayang** [sublimelsp/LSP-pyright#62]
lsp pyright do not support django stubs by default, variables like `objects` in django model are not recognized. I copied django stub files from vscode directory to sublime lsp-pyright directory, and created a METADATA.toml, It works.
from:
~/.vscode/extensions/ms-python.vscode-pylance-2021.3.3/dist/bundled/stubs/django
to:
~/.config/sublime-text-3/Package Storage/LSP-pyright/14.16.0/language-server/node_modules/pyright/dist/typeshed-fallback/stubs/django/django

The structure is here:
django
    |--- django   <------- copied from vscode directory
    |--- METADATA.toml
the content of METADATA.toml is:
```
version = "0.1"
python2 = true
python3 = true
```

But this is a dirty change to plugin and will be cleaned when the plugin upgrades. I noticed pyright supports `stubPath` setting, and there is a entry in LSP-pyright.sublime-settings `"python.analysis.stubPath": "./typings"`, so I tried to create a directory typings in my project directory and put the django stub directory which I created in previous step into typings directory, it not works. And I tried create a new directory and set stubPath pointing to it, not works also.

So can you help me to solve this problem? Or support django and some common packages like numpy, pandas, matplotlib directly in the LSP-pyright plugin?

**Comment by jfcherng** [comment]
> so I tried to create a directory typings in my project directory and put the django stub directory which I created in previous step into typings directory, it not works. And I tried create a new directory and set stubPath pointing to it, not works also.

Did you restart the server or ST?

**Comment by ayang** [comment]
Yes, I restarted ST.

**Comment by jfcherng** [comment]
```
project root dir
|--- typings
|   |--- django
|       |--- __init__.py
|       |--- ... many other dirs
|--- other project files/dirs
```

For the default settings, I think the above structure should work.

**Comment by ayang** [comment]
Great!!! Thank you!
