### ISSUE TITLE
autocomplete when using "import' command not working 

### ISSUE THREAD

**Issue by Trid-collab** [sublimelsp/LSP-pyright#64]
I am a newbie to this. 
I have Miniconda installed and have created environment. 
I have put in the path of the enev, lib, site- packages and conda path in my windows path 

I am getting autocomplete with every python command I using , expecting when using "import" when using sub
like when I am using "import matplotlib---> the autocomplete doesn't work when I am typing say "import mat"
But when I am using "from mat  ---> I am getting autocomplete. The autocomplete is also working when I am using other commands expecting import

my LSP-Pyright settings

```json
{


"languages":
	[
		{
			"languageId": "python",
			"scopes": ["source.python"],
		 	"syntaxes": ["Packages/Python/Python.sublime-syntax"]}
	],

"settings":	{
	"python.analysis.extraPaths": ["C:\\Users\\XXX\\Miniconda3\\envs\\py39k\\Lib\\site-packages\\"],
	"python.pythonPath": "C:\\Users\\XXX\\Miniconda3\\envs\\py39k\\",
	"python.venvPath": "C:\\Users\\xxx\\Miniconda3\\envs\\",
	"python.analysis.autoImportCompletions": true,
	"python.analysis.autoSearchPaths": true
	}
			
}
```

**Comment by rchl** [comment]
Have you tried https://github.com/sublimelsp/LSP-pyright#virtual-environments ?

**Comment by jfcherng** [comment]
Closed due to inactivity.
