### ISSUE TITLE
Autocompletion doesn't work for some variable

### ISSUE THREAD

**Issue by HJFG** [sublimelsp/LSP-pyright#67]
When I use fs module in code, the variable f can't get autocompletion, but it works well in my neovim lsp pyright with default setting.

```python
from fs import open_fs
f = open_fs('./')
f.glob('*.log').remove()

```

**Comment by jfcherng** [comment]
where is `open_fs` installed?

**Comment by HJFG** [comment]
> where is `open_fs` installed?

I'm using pyenv,so I find it in 
`/Users/houjue/.pyenv/versions/3.9.3/lib/python3.9/site-packages/fs`
and I installed fs via pip

**Comment by rchl** [comment]
Look at https://github.com/sublimelsp/LSP-pyright#virtual-environments on how to handle virtual environments (you'll need to create a pyright configuration file in your project).

**Comment by HJFG** [comment]
> Look at https://github.com/sublimelsp/LSP-pyright#virtual-environments on how to handle virtual environments (you'll need to create a pyright configuration file in your project).

Thanks for the useful link，but...you know sometimes I just like write some simple code without a virtualenv.

**Comment by rchl** [comment]
It's either virtual env or installing dependencies globally
