### ISSUE TITLE
Move "dev_environment" to "settings"

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-pyright#69]
The `dev_environment` setting should be a part of the `settings` object so that it's possible to override it from the project-specific settings.

The server won't mind an extra property that it doesn't understand.

**Comment by jfcherng** [comment]
Would you mind me using `lsp.dev_environment` as the key to indicate this setting doesn't come from the server?

**Comment by rchl** [comment]
Sounds a bit redundant but since naming is hard and I don't have better suggestion, I won't protest.

**Comment by jfcherng** [comment]
Consider that other lsp-* may will doing a similar thing someday in the future. It will be good to have a "standard" naming convention.

**Comment by rchl** [comment]
To be fair, for normal users that should be a non-issue to have no prefix. It's an option like any other and I'm not sure if distinction between "our" and server settings is necessary. The chance of conflict is very low I guess.
