### ISSUE TITLE
Is it possible to load libs from `.sublime-package` files?

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/LSP-pyright#71]
# Question

Just see this from the changelog of version `1.1.146`:

```
Enhancement (from pylance): Added support for libraries packages as zip/egg containers.
```

`.sublime-package` is just a `zip` file but with a different extension.

# References

- Pyright Changlog: https://github.com/microsoft/pyright/releases/tag/1.1.146
- Pylance discussion: https://github.com/microsoft/pylance-release/issues/1260

**Comment by rchl** [comment]
And the relevant change is https://github.com/microsoft/pyright/commit/e52d1e96e5d6cf4386504e0c1e1e708b84f227d9

Can't see a way to hook into that and handle *.sublime-package.

**Comment by jfcherng** [comment]
> And the relevant change is [microsoft/pyright@e52d1e9](https://github.com/microsoft/pyright/commit/e52d1e96e5d6cf4386504e0c1e1e708b84f227d9)
> 
> Can't see a way to hook into that and handle *.sublime-package.

Thanks. Not sure how it actually works but it hard-coded `zip` extension in https://github.com/microsoft/pyright/commit/e52d1e96e5d6cf4386504e0c1e1e708b84f227d9#diff-6f54fd7f4d0b2ea839407213f666d79d1d9e628196952f6c855e4da9ed2f3e78R138.

**Comment by jfcherng** [comment]
Not working after manually add `sublime-package` into that regex.
