### ISSUE TITLE
Bundle stub files for sublime.py and sublime_plugin.py

### ISSUE THREAD

**Issue by jwortmann** [sublimelsp/LSP-pyright#74]
If the setting *"pyright.dev_environment"* is used, it would be nice if Pyright could automatically provide stub files for `sublime.py` and `sublime_plugin.py`, for example from https://github.com/jfcherng-sublime/ST-API-stubs. Ideally, if `sublime.pyi`/`sublime_plugin.pyi` stubs are also found in `./typings` (or whatever the "python.analysis.stubPath" setting is set to), it would use the files from there instead of the bundled files.

**Comment by rchl** [comment]
Note that LSP would also have to use the same types as otherwise we would see re-defined type issues everywhere. Also, LSP types expose a bit more from the `typing` module so if we want to use @jfcherng's types, those would have to be extended also.

**Comment by rchl** [comment]
Or maybe I'm a bit confused. I was thinking about the `LSP/plugin/core/typing.py` file but this is about stubs.

**Comment by jwortmann** [comment]
Yeah LSP provides the same stub files in `LSP/stubs`. I wonder if there is a way to ignore the bundled stub files (if they'd be added to LSP-pyright) and only use the files provided by the user. Similar to how ST's override mechanism for files in the "Installed Packages"/"Packages" directory works.

**Comment by jfcherng** [comment]
Afaik, pyright looks up `extraPaths` in order and `./typings` seems to be always preferred.

**Comment by rchl** [comment]
Be careful though as it's easy to add type annotation somewhere and break the package because the type won't be present in "production".

Happen to do just that with Origami yesterday. :)
