### ISSUE TITLE
Error when starting pyright server: No "command" nor "tcp_port"

### ISSUE THREAD

**Issue by thewchan** [sublimelsp/LSP-pyright#75]
Getting this message whenever I start lsp-pyright on my project:
![image](https://user-images.githubusercontent.com/49702524/122591882-95cac180-d031-11eb-88c0-e9a74431c40a.png)

Windows 10; ST4 4107; Sublime-lsp: 1.6.0; LSP-pyright: 1.1.72

**Comment by rwols** [comment]
Looks like you don’t have a command set. Check the preferences of the LSP-pyright package.

**Comment by thewchan** [comment]
![image](https://user-images.githubusercontent.com/49702524/122596089-61f29a80-d037-11eb-8690-72bdc2389dc8.png)

Now I'm getting this instead, just on a test.py file with a single print statement

**Comment by thewchan** [comment]
I checked and those path exists

**Comment by rwols** [comment]
What other packages do you have installed?

try disabling LSP-pyright and then enabling LSP-pyright with package control. It’ll reinstall the server files.

**Comment by thewchan** [comment]
I have tried removing lsp and installing lsp, removing lsp-pyright and install lsp-pyright. Here are a list of packages:

'A File Icon.sublime-package'
Alignment.sublime-package
AutoDocstring.sublime-package
BracketHighlighter.sublime-package
ChangeQuotes.sublime-package
'Color Highlight.sublime-package'
Djaneiro.sublime-package
'Dockerfile Syntax Highlighting.sublime-package'
Emmet.sublime-package
Git.sublime-package
HTML5.sublime-package
INI.sublime-package
LSP-css.sublime-package
LSP-html.sublime-package
LSP-json.sublime-package
LSP-lemminx.sublime-package
LSP-pyright.sublime-package
LSP-stylelint.sublime-package
LSP.sublime-package
'Markdown Extended.sublime-package'
MarkdownPreview.sublime-package
'Material Theme.sublime-package'
Origami.sublime-package
'Package Control.sublime-package'
PackageDev.sublime-package
PowerShell.sublime-package
'PyYapf Python Formatter.sublime-package'
QuickView.sublime-package
RegexExplainTip.sublime-package
'Show Unicode Name.sublime-package'
SideBarEnhancements.sublime-package
'Smart Title Case.sublime-package'
SubLilyPond.sublime-package
SublimeLinter-contrib-bashate.sublime-package
SublimeLinter-contrib-htmlhint.sublime-package
SublimeLinter-contrib-yamllint.sublime-package
SublimeLinter-csslint.sublime-package
SublimeLinter-flake8.sublime-package
SublimeLinter-json.sublime-package
SublimeLinter-mdl.sublime-package
SublimeLinter-php.sublime-package
SublimeLinter-pydocstyle.sublime-package
SublimeLinter-pylint.sublime-package
SublimeLinter-xmllint.sublime-package
SublimeLinter.sublime-package
Terminus.sublime-package
'View In Browser.sublime-package'
jQuery.sublime-package
nginx.sublime-package
requirementstxt.sublime-package
sublack.sublime-package

**Comment by rchl** [comment]
`LSP: Troubleshoot Server` from the Command Palette might give some clue. Especially if there is some `output`.

**Comment by thewchan** [comment]
# Troubleshooting: LSP-pyright
## Version
 - LSP: 1.6.0
 - Sublime Text: 4107
## Server Test Run
 - exit code: 1
 - output
```
node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module './dist/pyright-langserver'
Require stack:
- C:\Users\mchan811\AppData\Local\Sublime Text\Package Storage\LSP-pyright\16.3.0\language-server\node_modules\pyright\langserver.index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (C:\Users\mchan811\AppData\Local\Sublime Text\Package Storage\LSP-pyright\16.3.0\language-server\node_modules\pyright\langserver.index.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\mchan811\\AppData\\Local\\Sublime Text\\Package Storage\\LSP-pyright\\16.3.0\\language-server\\node_modules\\pyright\\langserver.index.js'
  ]
}
```
## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh
"C:\Program Files\nodejs\node.EXE" "C:\Users\mchan811\AppData\Local\Sublime Text\Package Storage\LSP-pyright\16.3.0\language-server\node_modules\pyright\langserver.index.js" --stdio
```
 - selector
```
source.python
```
 - priority_selector
```
source.python
```
 - init_options
```json
{}
```
 - settings
```json
{
  "pyright": {
    "dev_environment": "", 
    "disableLanguageServices": false, 
    "disableOrganizeImports": false
  }, 
  "python": {
    "analysis": {
      "autoImportCompletions": true, 
      "autoSearchPaths": true, 
      "diagnosticMode": "openFilesOnly", 
      "diagnosticSeverityOverrides": {
        "reportDuplicateImport ": "warning", 
        "reportImplicitStringConcatenation": "warning", 
        "reportUnboundVariable": "warning", 
        "reportUnusedClass": "information", 
        "reportUnusedFunction": "information", 
        "reportUnusedImport": "information", 
        "reportUnusedVariable": "information"
      }, 
      "extraPaths": [], 
      "logLevel": "information", 
      "stubPath": "./typings", 
      "typeCheckingMode": "basic", 
      "typeshedPaths": [], 
      "useLibraryCodeForTypes": true
    }, 
    "pythonPath": "python", 
    "venvPath": ""
  }
}
```
 - env
```json
{
  "PATH": "C:\\Program Files\\nodejs;"
}
```

## Active view
 - File name
```
C:\Users\mchan811\OneDrive - Comcast\Desktop\test.py
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/Djaneiro/Syntaxes/Python Django.tmLanguage"
}
```
 - base scope
```
source.python.django
```

## Project / Workspace
 - folders
```json
[]
```
 - is project: False

## LSP configuration

```json
{
  "diagnostics_gutter_marker": "sign", 
  "document_highlight_style": "fill", 
  "log_debug": true, 
  "log_server": [
    "panel"
  ], 
  "show_diagnostics_count_in_view_status": true, 
  "show_diagnostics_panel_on_save": 4, 
  "show_references_in_quick_panel": true
}
```
## System PATH
 - C:\tools\ruby30\bin
 - C:\ProgramData\Oracle\Java\javapath
 - C:\WINDOWS\system32
 - C:\WINDOWS
 - C:\WINDOWS\System32\Wbem
 - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
 - C:\ProgramData\chocolatey\bin
 - C:\ProgramData\chocolatey\lib\gsudo\bin\
 - C:\tools\BCURRAN3
 - C:\Program Files\Git LFS
 - C:\Program Files\MiKTeX\miktex\bin\x64\
 - C:\Program Files\Amazon\AWSCLIV2\
 - C:\Program Files\Java\jdk1.8.0_211\bin
 - C:\Program Files\LLVM\bin
 - C:\tools\libxml
 - C:\tools\fly\
 - C:\tools\bucc\bin
 - C:\tools\aws
 - C:\WINDOWS\System32\OpenSSH\
 - C:\tools\geckodriver
 - C:\tools\php80
 - C:\Program Files (x86)\Sennheiser\SenncomSDK\
 - C:\Program Files (x86)\scala\bin
 - C:\tools\ammonite
 - C:\Program Files\Calibre2\
 - C:\Program Files\OpenJDK\openjdk-11.0.11_9\bin
 - C:\Program Files\OpenJDK\openjdk-8u292-b10-jre\bin
 - C:\Program Files\PowerShell\7\
 - C:\Program Files\Sublime Text\
 - C:\Program Files\nodejs\
 - C:\Program Files\Git\cmd
 - C:\Program Files\Docker\Docker\resources\bin
 - C:\ProgramData\DockerDesktop\version-bin
 - C:\Users\mchan811\AppData\Local\Microsoft\WindowsApps
 - C:\Users\mchan811\AppData\Local\Pandoc\
 - C:\Users\mchan811\.local\bin
 - C:\Program Files\Oracle\VirtualBox
 - C:\tools\neovim\Neovim\bin
 - C:\tools\dart-sdk\bin
 - C:\Users\mchan811\AppData\Roaming\Pub\Cache\bin
 - C:\Users\mchan811\AppData\Local\Coursier\data\bin
 - C:\Users\mchan811\null\Coursier\data\bin
 - C:\Users\mchan811\null\Coursier\cache\jvm\adopt@1.11.0-11\bin
 - C:\Users\mchan811\AppData\Roaming\npm

**Comment by rchl** [comment]
Try uninstalling the package and installing again, only watch the ST console when it's starting for the first time. It will print information when it's installing the server and there might be some error there.

@rwols Disabling the package no longer deletes the server so suggesting that won't work.

**Comment by thewchan** [comment]
okay I'll try that

**Comment by thewchan** [comment]
Uninstall messages:
```
ignored packages updated to: ["LSP-pyright", "Vintage"]
unloading python 3.3 plugin LSP-pyright.commands
reloading settings Packages/LSP-pyright/LSP-pyright.sublime-settings
unloading python 3.3 plugin LSP-pyright.plugin
reloading settings Packages/User/Package Control.sublime-settings
Traceback (most recent call last):
  File "C:\Users\mchan811\AppData\Roaming\Sublime Text\Installed Packages\Package Control.sublime-package\package_control/thread_progress.py", line 27, in <lambda>
  File "C:\Users\mchan811\AppData\Roaming\Sublime Text\Installed Packages\Package Control.sublime-package\package_control/thread_progress.py", line 51, in run
AttributeError: 'NoneType' object has no attribute 'set_status'
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The package LSP-pyright has been removed
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
```

**Comment by thewchan** [comment]
Re-install messages:
```
ignored packages updated to: ["LSP-pyright", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "C:\Users\mchan811\AppData\Roaming\Sublime Text\Installed Packages\Package Control.sublime-package\package_control/thread_progress.py", line 27, in <lambda>
  File "C:\Users\mchan811\AppData\Roaming\Sublime Text\Installed Packages\Package Control.sublime-package\package_control/thread_progress.py", line 51, in run
AttributeError: 'NoneType' object has no attribute 'set_status'
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading python 3.3 plugin LSP-pyright.commands
reloading python 3.3 plugin LSP-pyright.plugin
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by rchl** [comment]
And then the messages on the first open of python file after installing?

**Comment by thewchan** [comment]
??? Now it works?

**Comment by thewchan** [comment]
![image](https://user-images.githubusercontent.com/49702524/122603440-5062c000-d042-11eb-8f78-ab3bb3d28569.png)

**Comment by thewchan** [comment]
I'm so confused...

**Comment by rchl** [comment]
That makes sense. Uninstalling the package has removed the server files that apparently got partially installed on the previous try.

**Comment by thewchan** [comment]
If I open my previous python project though, I still get this:

![image](https://user-images.githubusercontent.com/49702524/122604067-5ad18980-d043-11eb-9f18-f7ed3c84cbd9.png)

**Comment by rchl** [comment]
That project appears to have custom `lsp-pyright` config, probably in the project file. Note how the `lsp` is in lowercase while the real `LSP-pyright` would have different case.

**Comment by thewchan** [comment]
Here's the project config
```json
{
	"folders":
	[
		{
			"path": "C:\\Users\\mchan811\\github-repos\\pypabs",
		}
	],
	"settings": {
		"python_interpreter": "C:\\tools\\miniconda3\\envs\\pypabs-dev\\python.exe",
		"SublimeLinter.linters.pylint.executable": "C:\\tools\\miniconda3\\envs\\pypabs-dev\\Scripts\\pylint.exe",
		"SublimeLinter.linters.flake8.executable": "C:\\tools\\miniconda3\\envs\\pypabs-dev\\Scripts\\flake8.exe",
		"SublimeLinter.linters.pylint.args": "--disable=E0401,E0611",
		"SublimeLinter.linters.flake8.args": "--ignore=F407",
		"LSP": {
			"Lsp-pyright": {
				"selector": "source.python",
				"settings": {
					"pyright.disableLanguageServices": false,
					"pyright.disableOrganizeImports": false,
					"python.analysis.autoImportCompletions": true,
					"python.analysis.autoSearchPaths": true,
					"python.analysis.diagnosticMode": "openFilesOnly",
					"python.analysis.diagnosticSeverityOverrides": {
						"reportCallInDefaultInitializer": "information",
						"reportConstantRedefinition": "information",
						"reportDuplicateImport ": "warning",
						"reportFunctionMemberAccess": "warning",
						"reportImplicitStringConcatenation": "warning",
						"reportImportCycles": "warning",
						"reportIncompatibleMethodOverride": "warning",
						"reportIncompatibleVariableOverride": "warning",
						"reportIncompleteStub": "information",
						"reportInvalidStubStatement": "information",
						"reportInvalidTypeVarUse": "warning",
						"reportMissingImports": "warning",
						"reportMissingTypeArgument": "information",
						"reportMissingTypeStubs": "warning",
						"reportOptionalCall": "warning",
						"reportOptionalContextManager": "warning",
						"reportOptionalIterable": "warning",
						"reportOptionalMemberAccess": "warning",
						"reportOptionalOperand": "warning",
						"reportOptionalSubscript": "warning",
						"reportOverlappingOverload": "warning",
						"reportPrivateUsage": "information",
						"reportUnboundVariable": "warning",
						"reportUnknownArgumentType": "information",
						"reportUnknownLambdaType": "information",
						"reportUnknownMemberType": "information",
						"reportUnknownParameterType": "information",
						"reportUnknownVariableType": "information",
						"reportUnnecessaryCast": "information",
						"reportUnnecessaryComparison": "information",
						"reportUnnecessaryIsInstance": "information",
						"reportUntypedBaseClass": "warning",
						"reportUntypedClassDecorator": "warning",
						"reportUntypedFunctionDecorator": "warning",
						"reportUntypedNamedTuple": "warning",
						"reportUnusedCallResult": "information",
						"reportUnusedClass": "information",
						"reportUnusedFunction": "information",
						"reportUnusedImport": "information",
						"reportUnusedVariable": "information",
						"reportWildcardImportFromLibrary": "warning",
					},
					"python.analysis.extraPaths": ["C:\\Users\\mchan811\\github-repos\\pypabs-dev"],
					"python.analysis.logLevel": "information",
					"python.analysis.strictDictionaryInference": true,
					"python.analysis.strictListInference": true,
					"python.analysis.strictParameterNoneValue": true,
					"python.analysis.strictSetInference": true,
					"python.analysis.stubPath": "./typings",
					"python.analysis.typeCheckingMode": "basic",
					"python.analysis.typeshedPaths": [],
					"python.analysis.useLibraryCodeForTypes": true,
					"python.pythonPath": "C:\\tools\\miniconda3\\envs\\pypabs-dev\\python.exe",
					"python.venvPath": "C:\\tools\\miniconda3\\envs",
					"python.venv": "pypabs-dev",
				},
				"enabled": true,
			},
		},
	},
}
```

**Comment by thewchan** [comment]
I guess I need to modify `lsp` to `LSP`?

**Comment by thewchan** [comment]
I think that was it! It works now! I think a lot of the parameters in the config might be wrong or something because I'm getting a lot of `not allowed` type diagnostics
![image](https://user-images.githubusercontent.com/49702524/122604530-15618c00-d044-11eb-8b86-c31cc9d52584.png)

**Comment by rchl** [comment]
You are unnecessarily overriding a lot of settings of LSP-pyright. You only need to override the settings that you want to change, not everything. And yes, those settings that are marked with diagnostics are not valid settings.

**Comment by rchl** [comment]
Look at the readme (https://github.com/sublimelsp/LSP-pyright) to see how to configure it for your virtual environment.

**Comment by rwols** [comment]
If you now change "Lsp-pyright" to "LSP-pyright" (note the casing) in your project settings, that config in your project will override the base LSP-pyright again, as intended.

**Comment by thewchan** [comment]
Yeah I think someone copied and pasted a lot of the LSP config from the pyright github repo, probably a little over zealous
