### ISSUE TITLE
Buggy autocomplete for relative local imports

### ISSUE THREAD

**Issue by maegul** [sublimelsp/LSP-pyright#76]
Autocomplete is providing incorrect options when importing from local directories with a relative import.

At first, only the already imported top-level import is listed as an option.  Then, once the first character of any of the actual sub-directories or modules is typed, the autocomplete will refresh with appropriate options.  See images below.

I've been seeing this a few versions of LSP-pyright now.  Unsure whether this is more appropriate over in the pyright repo.

Sublime Text: 4106 (Dev Channel)
LSP: 1.6.1
LSP-Pyright: 1.1.73
OS: MacOS 10.14.5

![Screen Shot 2021-06-22 at 12 18 04 am](https://user-images.githubusercontent.com/13930443/122778214-1e768580-d2f0-11eb-80af-1bb4c198e045.png)

![Screen Shot 2021-06-22 at 12 18 33 am](https://user-images.githubusercontent.com/13930443/122778257-2a624780-d2f0-11eb-9d80-280409981603.png)

![Screen Shot 2021-06-22 at 12 18 49 am](https://user-images.githubusercontent.com/13930443/122778315-3e0dae00-d2f0-11eb-8cf3-eb0ead3bd951.png)
![Screen Shot 2021-06-22 at 12 19 08 am](https://user-images.githubusercontent.com/13930443/122778365-4960d980-d2f0-11eb-8db2-2900d24a8a00.png)

The problem doesn't seem to occur with absolute imports

![Screen Shot 2021-06-22 at 12 20 31 am](https://user-images.githubusercontent.com/13930443/122778839-ac527080-d2f0-11eb-81a5-429961147052.png)

**Comment by jfcherng** [comment]
This should be either an issue for pyright or LSP but LSP usually just show what pyright returns. Either way, I don't think this is a LSP-pyright issue.

**Comment by jfcherng** [comment]
By the way, VSCode behaves the same.
