### ISSUE TITLE
Renaming does not work in Sublime Text 4

### ISSUE THREAD

**Issue by L117** [sublimelsp/LSP-pyright#79]
To reproduce:

1. Open single python file (Without venv, project directory, etc.).
2. Click on some function name.
3. Select LSP > Rename...
4. Enter new name
5. Hit enter
6. See "Nothing to rename" in status bar.

**Comment by jfcherng** [comment]
I'm not infront of a PC, but LSP servers work best under a folder(project) rather than a single file.

**Comment by rchl** [comment]
And if you disagree you can try your luck reporting it in https://github.com/microsoft/pyright (check if there were or are existing issues like that).
