### ISSUE TITLE
Autocomplete: issue with trailing symbols

### ISSUE THREAD

**Issue by glubbfreund** [sublimelsp/LSP-pyright#80]
Hi,

see: https://forum.sublimetext.com/t/autocomplete-trailing-symbols/59677/6

With ST4 it should be possible to autocomplete the following function with brackets (and jump inside the brackets)
def foo(text: str):
print(text)

foo();
fo -> completes to foo only and doesnt jump inside the brackets

same issue with LSP-pylsp as mentioned in the forum post above.

**Comment by jfcherng** [comment]
Wondering should this be a general question that is not specific to pyright.

Interestingly, it's available in pylance...

```
python.analysis.completeFunctionParens

Add parentheses to function completions.
Accepted values:
    true
    false (default)
```

**Comment by glubbfreund** [comment]
I opened an issue in the lsp github, you can reproduce it if you uninstall your package. It seems that the safe mode doesnt fix it, but I dont know why

**Comment by jfcherng** [comment]
> I opened an issue in the lsp github, you can reproduce it if you uninstall your package. It seems that the safe mode doesnt fix it, but I dont know why

Yes, that's the weird part. Safe mode has no package at all.

**Comment by glubbfreund** [comment]
yep :) very confusing...

**Comment by rwols** [comment]
This is just how pylsp presents its completions. By default LSP supresses the default word completions as they can turn into a word salad for larger projects. You can opt to enable them by setting `"inhibit_word_completions"` to `false` in Packages/User/LSP.sublime-settings, reachable via _Preferences: LSP Settings_ in the Command Palette.
