### ISSUE TITLE
[Question] Setting for completion of function parens

### ISSUE THREAD

**Issue by ivanddm** [sublimelsp/LSP-pyright#81]
I'm wondering if there is a setting to have function calls autocompletion of parenthesis ala VSCode or Coc-pylsp. For example, a setting such as `"python.analysis.completeFunctionParens": true` and `"python.autoComplete.addBrackets": true`.

Thanks in advance!

**Comment by jfcherng** [comment]
`"python.analysis.completeFunctionParens": true` only works in Pylance unfortuantaely.

**Comment by ivanddm** [comment]
Thanks for letting me know. Still, I'm quite happy with the implementation of pyright in Sublime. Thanks for your work!
