### ISSUE TITLE
pyrightconfig.json is not found depending on configured project folders

### ISSUE THREAD

**Issue by huljar** [sublimelsp/LSP-pyright#82]
Hi all,

I have a python project set up that has the following structure:
```
myProject/
|_ project/
   |_ main.py
|_ pyrightconfig.json
|_ myProject.sublime-project
```
Now, if I configure ``myProject.sublime-project`` like this:
```
{
    "folders":
    [
        {
            "path": ".",
        }
    ],
}
```
then pyright successfully finds the config file and parses it.
<details>
<summary>LSP output</summary>

```
LSP-pyright: Pyright language server 1.1.162 starting
LSP-pyright: Server root directory: /home/<redacted>/.cache/sublime-text/Package Storage/LSP-pyright/12.22.5/language-server/node_modules/pyright/dist/
LSP-pyright: Loading configuration file at /home/<redacted>/dev/myProject/pyrightconfig.json
LSP-pyright: Unable to get Python version from interpreter
LSP-pyright: Assuming Python platform Linux
LSP-pyright: No include entries specified; assuming /home/<redacted>/dev/myProject
LSP-pyright: Auto-excluding **/node_modules
LSP-pyright: Auto-excluding **/__pycache__
LSP-pyright: Auto-excluding .git
LSP-pyright: stubPath /home/<redacted>/dev/myProject/typings is not a valid directory.
LSP-pyright: Searching for source files
LSP-pyright: Auto-excluding /home/<redacted>/dev/myProject/.venv
LSP-pyright: Found 6 source files
```
</details>

However, if I configure it to just show the contents of ``project/`` in the sidebar (e.g., because I don't want to see all the auxiliary files in the project root and just focus on the sources), then it doesn't work any more and the ``pyrightconfig.json`` is no longer found.
```
{
    "folders":
    [
        {
            "path": "project",
        }
    ],
}
```
<details>
<summary>LSP output</summary>

```
LSP-pyright: Pyright language server 1.1.162 starting
LSP-pyright: Server root directory: /home/<redacted>/.cache/sublime-text/Package Storage/LSP-pyright/12.22.5/language-server/node_modules/pyright/dist/
LSP-pyright: No configuration file found.
LSP-pyright: No pyproject.toml file found.
LSP-pyright: stubPath /home/<redacted>/dev/myProject/project/typings is not a valid directory.
LSP-pyright: Assuming Python platform Linux
LSP-pyright: Searching for source files
LSP-pyright: Found 5 source files
```
</details>

Judging by the output, it seems like in the second example, the ``project/`` subdir is assumed to be the project root. However, I'd expect LSP to always use the actual project root (i.e., the directory that contains the ``.sublime-project`` file) as root, no matter how the folders are configured inside of the project. Consequently, I'd expect the ``pyrightconfig.json`` to be found in both cases.

**Comment by jfcherng** [comment]
If this is how it (pylance) works in VSCode, then this is an upstream issue. (I didn't test.)

**Comment by rwols** [comment]
> However, I'd expect LSP to always use the actual project root (i.e., the directory that contains the .sublime-project file) as root

.sublime-project files do not signify a project root. Someone could have a bunch of .sublime-project files in ~/Desktop/ pointing to “real” project roots.

**Comment by jfcherng** [comment]
Closed since this is a upstream issue.
