### ISSUE TITLE
Something confused about settings

### ISSUE THREAD

**Issue by sttv9998877** [sublimelsp/LSP-pyright#84]
I'm now using Debian system and sumlime_text to code with python
There are some settings I need to change to adapt my project file
But when I modified the setting, it had not overridden the old one
And I search the path of setting file, found that nothing existed there, including the folder "LSP-pyright", I must create it by myself and write the settings directly in this file
Is that a bug, or it rightly would not initiate this aspect?

**Comment by jfcherng** [comment]
> And I search the path of setting file, found that nothing existed there, including the folder "LSP-pyright", I must create it by myself and write the settings directly in this file

You can open the settings file here:

![Snipaste_2021-09-09_16-54-34](https://user-images.githubusercontent.com/6594915/132655266-4b8a6e9c-b9ce-441d-b262-5f2a923d22a0.png)

Anyway, LSP-pyright is not going to delete any settings file no matter how it's created.

**Comment by sttv9998877** [comment]
Yeah，I open setting file in this way.And when I saved my setting it didn't overridden my configurationI right-clicked the setting tap to find the original file.But there was nothing where the path pointing to(packages/*).I assumedthat the setting file would be created automatically when installed with the unit value，but it didn't，is that normal？On Sep 9, 2021 16:55, Jack Cherng ***@***.***> wrote:

And I search the path of setting file, found that nothing existed there, including the folder "LSP-pyright", I must create it by myself and write the settings directly in this file

You can open the settings file here:

Anyway, LSP-pyright is not going to delete any settings file no matter how it's created.

**Comment by jfcherng** [comment]
The settings file should be `Packages/User/LSP-pyright.sublime-settings`

**Comment by sttv9998877** [comment]
Yeah,but mine is a little different from the path you showed
/home/xxx/.config/sublime-text/Packages/LSP/LSP.sublime-settings
My syetme is linux



As you see,I click this and open my default path it copied "/home/yorc/.config/sublime-text/Packages/LSP-pyright/LSP-pyright.sublime-settings"into my clipborad but "/Packages/LSP-py-right/" did not exist ,I manully create that folder and file "LSP-pyright.sublime-settings" in it,but when I modified the setting at right tap like below, it didn't override yet.So I have to type derectly in settings file I created myself, it finally works







At 2021-09-10 08:46:37, "Jack Cherng" ***@***.***> wrote:

The settings file should be Packages/User/LSP-pyright.sublime-settings

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jfcherng** [comment]
> /home/xxx/.config/sublime-text/Packages/LSP/LSP.sublime-settings

Obviously, this is `LPS`'s config. Not `LSP-pyright`'s.

> My syetme is linux

That's irrelevant.

> As you see, ...

Not sure what you are doing there. The suggested way to edit `LSP-pyright`'s settings is https://github.com/sublimelsp/LSP-pyright/issues/84#issuecomment-915894438. If you want to do it manually but gets messed up, then I think that's your own problem.

**Comment by sttv9998877** [comment]
OK, thanks to reply
