### ISSUE TITLE
Missing imports reported for venv packages, but only on project subdirectories

### ISSUE THREAD

**Issue by mconigliaro** [sublimelsp/LSP-pyright#88]
I have a pretty standard project structure:

```
.
├── .venv
├── my_project
│   ├── __init__.py
├── bin
│   └── my_script
└── tests
│   └── test_something.py
```

I've noticed that everything works fine on files in my `my_project` directory (with no pyright configuration), but when I look at files in any of the subdirectories (e.g. `bin/`, `test/`), imports for packages I've `pipenv install`-ed (into my local `.venv`) get the `reportMissingImports` error. I did try to configure virtual environments as described in the LSP-pyright documentation, but it didn't seem to help (I'm not sure it's actually required anymore, because my venv seems to be detected automatically without it). I also noticed that I don't get these errors when I run `pyright` against the affected files on the command line.

**Comment by mconigliaro** [comment]
Quick correction: Something in the CLI output originally made me think my venv was automatically discovered, but I was wrong. I also realized my editor didn't have the same environment as my shell, so after exiting my pipenv shell, I had to add the following to `pyproject.toml` to make the import errors go away on the command line:

```toml
[tool.pyright]
venvPath = "."
venv = ".venv"
```

The following also works in `pyrightconfig.json` (**not** `.pyrightconfig.json` as currently documented in part of the README):

```json
{
    "venvPath": ".",
    "venv": ".venv"
}
```

I don't understand why my other project has that specific behavior where I only get the `reportMissingImports` warning in certain directories, but [here's one](https://github.com/mconigliaro/cellular_automata) where I get the error for every venv-installed library, no matter which file I look at. This only happens inside Sublime Text. When I run `pyright` on the CLI (whether inside my pipenv shell or not), I see other warnings, but nothing about missing imports.

**Comment by rchl** [comment]
While I don't know much about working with virtual environments, following the instructions in the readme for that project, there is no .venv directory being created inside the project. Where is it created then? It should be withing the project so that the pyright configuration can find it.

**Comment by rchl** [comment]
BTW. The one place in the LSP-pyright readme where it mentions `.pyrightconfig.json` is a typo. All other places mention `pyrightconfig.json`. I've just pushed a fix for that.

**Comment by rchl** [comment]
Servers generally prefer when individual projects are opened independently.

Many servers only read configuration files from the root of the project (or workspace) for example. I believe this is what is happening here also. The `pyrightconfig.json` (or the `pyproject.toml` equivalent) is likely only supported at the root of the project.

**Comment by mconigliaro** [comment]
Makes sense. Originally, the importance of finding the root of the project didn't occur to me.
