### ISSUE TITLE
New upstream preferences

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-pyright#89]
In the latest release notes I saw:

> Added new diagnostic check "reportMissingParameterType" that checks for function and method input parameters that are missing a type annotation.

Not sure if there were any other than that added since we've updated settings.

**Comment by jfcherng** [comment]
Done in https://github.com/sublimelsp/LSP-pyright/commit/ae57633a92a80885e88e871d16fadebccd8c7389
