### ISSUE TITLE
Support ST3

### ISSUE THREAD

**Issue by AmjadHD** [sublimelsp/LSP-pyright#9]
Is there a reason for not supporting ST3 ?

**Comment by jfcherng** [comment]
I think no as long as someone is going to maintain a ST 3 version of `LSP-pyright.sublime-settings`. There should be no reason that a LSP-* **must** only support ST 3 I guess.

**Comment by rchl** [comment]
PRs welcome. :)
But yeah, we would need a separate for ST3 version just so that we can use non-dotted settings format.

**Comment by jfcherng** [comment]
Iirc I saw a LSP-* plugin write ST3/ST4 settings together since they are not affected by each other.

**Comment by rchl** [comment]
Normal `dict` doesn't guarantee key order so I think that would be unreliable, at best.

**Comment by jfcherng** [comment]
:thinking: weird. this issue is not auto closed.
waiting for https://github.com/wbond/package_control_channel/pull/8024
