### ISSUE TITLE
Goto definition goes to stub files instead of actual definitions

### ISSUE THREAD

**Issue by kylebebak** [sublimelsp/LSP-pyright#90]
This makes code navigation in the standard library a lot less useful. In the standard library there are no inlined type annotations; there are type stubs for everything, **which means LSP-pyright won't show you doc strings for anything in the standard library**. It also makes code navigation in 3rd party libraries that use type stubs instead of inlined type annotations a lot less useful, for the same reason.

This is basically a duplicate of these pylance issues:

- https://github.com/microsoft/pylance-release/issues/65
- https://github.com/microsoft/pylance-release/issues/949

I know that pylance is powered by `pyright`, but `pylance` may be doing additional work to prevent this behavior. Hopefully making a similar change to LSP-pyright is possible.

-----

Here are some screenshots. First, the hover menu with LSP options

<img width="1115" alt="Screen Shot 2021-10-18 at 9 32 58 AM" src="https://user-images.githubusercontent.com/1524088/137752581-219e3e1e-9e32-45e1-84a3-f840d8a3533d.png">

Then, after clicking on **Definition**, one is taken here

<img width="496" alt="Screen Shot 2021-10-18 at 9 33 08 AM" src="https://user-images.githubusercontent.com/1524088/137752603-72f34040-fb1e-4f20-858d-840b621e46f5.png">

It would be awesome if **Definition** took one to the source code, where you could read the `list.pop` docstring, and **Declaration** took you to the type stubs if they exist. What would be even more awesome would be to see the type annotations for the function **and** the docstring in the hover menu

And thank you so much for maintaining this plugin and the LSP plugin, they've made my life a lot better

@jfcherng @rwols @rchl

**Comment by kylebebak** [comment]
Thanks for explaining this @jfcherng . Given that `pyright` doesn't support goto definition in the way I'd like it to, I think the easiest solution is to supplement pyright with another LSP server, e.g. https://github.com/pappasam/jedi-language-server, that prefers source code over type annotations for goto definition

**Comment by kylebebak** [comment]
One last idea. Here's a duplicate issue in `pyright`, not `pylance`

- https://github.com/microsoft/pyright/issues/795

According to pyright's maintainer, it seems that for third party code (and maybe for standard library code as well), `pyright` **is** capable of returning definitions for both type annotations and source code.

>If you have both a type stub (including those that ship as part of typeshed) and a library implementation is present, Pyright will show you the definition in both locations, and you can choose between them. For example, see this screen shot.

That said, there are other messages in that issue that suggest this doesn't work. If pyright can return multiple results for goto definition, maybe LSP-pyright can surface them both in the hover menu

**Comment by kylebebak** [comment]
@jwortmann 

You're right. I tried using Jedi, and it jumped to the same definitions that LSP-pyright did. I don't think there's any easy solve for this.

For builtins like `list.pop`, I'm not sure where a plugin could pull definitions from. The cpython source code, maybe, but that doesn't seem like pyright's job.

**Comment by jfcherng** [comment]
Seems to be resolved or non-goal.

**Comment by Suor** [comment]
Still having this issue
