### ISSUE TITLE
Use the `--skipunannotated` option

### ISSUE THREAD

**Issue by AmjadHD** [sublimelsp/LSP-pyright#91]
From pyright 1.8.1 release notes:
> Enhancement: Added "--skipunannotated" option for command-line version of pyright. If specified, pyright skips type analysis of functions and methods that have no parameter or return type annotations. Return types of functions are also never inferred from the function implementation. This matches the default behavior of mypy and allows for more efficient analysis of complex code bases that are only partially annotated.

maybe use this ?

**Comment by jfcherng** [comment]
Closed due to inactivity.
