### ISSUE TITLE
Rename feature seems to do nothing

### ISSUE THREAD

**Issue by oerp-odoo** [sublimelsp/LSP-pyright#95]
When I hover over variable, for example, I see `RENAME` option, when I click it I get pop up where it allows me to change name. Though after changing it and pressing ENTER, nothing happens.

What that RENAME option supposed to do?
![Selection_188](https://user-images.githubusercontent.com/7812986/140977504-ccaefeea-6abb-4a6e-9767-92f4e2609a78.png)

**Comment by jfcherng** [comment]
hmmm... works for me, even if in a single file (non-project) case.

**Comment by rchl** [comment]
Enabling `log_server` (https://lsp.sublimetext.io/troubleshooting/) might reveal something.

**Comment by predragnikolic** [comment]
Cannot reproduce,
can we close this?

**Comment by jfcherng** [comment]
Closed because can't reproduce and inactiveness.

**Comment by rchl** [comment]
It was reproducible :)
But it was fixed in LSP and I've also added a small note to the readme: f36a6e3b6659398c392f83e2b6449b430a4be2c5
