### ISSUE TITLE
wrong arg name for `r` in `self.view.replace` of `sublime.pyi`

### ISSUE THREAD

**Issue by jrappen** [sublimelsp/LSP-pyright#97]
In `sublime.pyi` it's:

```python
self.view.replace(edit, r, text)
```

not:

```python
self.view.replace(edit, region, text)
```

**Comment by jfcherng** [comment]
it follows the name in .py

```py
    def replace(self, edit, r, text):
        if edit.edit_token == 0:
            raise ValueError("Edit objects may not be used after the TextCommand's run method has returned")

        sublime_api.view_replace(self.view_id, edit.edit_token, r, text)
```

**Comment by jrappen** [comment]
I know what it should be. The current LSP-pyright chockes on `r` though and tells me to use `region` instead.

**Comment by jrappen** [comment]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/8577450/141486730-0558de38-5139-43e6-9131-1bd43a355500.png">

**Comment by jfcherng** [comment]
Oops, there seems to be more things like this. I have to check.

**Comment by jfcherng** [comment]
Fixed in 49c0e8b. It turns out to be `r` is actually the minor. Only 3 places use `r`. Well spotted!

**Comment by jrappen** [comment]
so, ... do I just clear my cache and restart for a reload?

**Comment by jfcherng** [comment]
> so, ... do I just clear my cache and restart for a reload?

I didn't tag a release as I think pyright is releasing a new version quite frequently. If you you want to fix it locally now, maybe fix them in `Data\Package Storage\LSP-pyright\resources\typings\sublime_text`.

**Comment by jrappen** [comment]
ok thanks
