### ISSUE TITLE
Strict type-checking mode won't work

### ISSUE THREAD

**Issue by Marshblocker** [sublimelsp/LSP-pyright#98]
I have installed LSP and LSP-pyright in Sublime Text 4 and included `"python.analysis.typeCheckingMode": "strict"` within the `LSP-pyright.sublime-settings` file but `Pyright` still won't raise any Type error when I wrote the following code:

```python
def foo(x, y):
    return x + y
```
To add, it seems the basic type-checking mode still work since the code 
```python
import unknownpackage
``` 
makes Pyright raise `reportMissingImports`. So what seems to be the problem?

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/142357303-d678bf95-96e3-47b7-ab6a-217e4b7a1e44.png)

```js
// Settings in here override those in "LSP-pyright/LSP-pyright.sublime-settings"

{
	"settings": {
		"python.analysis.typeCheckingMode": "strict"
	}
}
```
