### ISSUE TITLE
Error starting server: "lock file's pyright@1.1.187 does not satisfy pyright@^1.1.188"

### ISSUE THREAD

**Issue by dcyoung05** [sublimelsp/LSP-pyright#99]
Looks like package-lock.json wasn't updated to match package.json in https://github.com/sublimelsp/LSP-pyright/commit/2934a8ba76074a5ebe10279dfc182412911454f9.

**Comment by rchl** [comment]
Thanks.
Released 1.1.111 with a fix.

@jfcherng maybe time for some automation for that? Or wait for dependabot? If you want to release ASAP then a manually triggered workflow could probably do the job.

**Comment by jfcherng** [comment]
I decide to unwatch pyright's release so it will be managed by the depbot.
